// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"
	"time"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// AuditLogInterface is the contract implemented by *services.AuditLogService and its
// logging / telemetry decorators.
type AuditLogInterface interface {
	List(ctx context.Context, orgID uuid.UUID, entityType string, entityID string, action string, from *time.Time, to *time.Time, page int, pageSize int) ([]models.AuditLog, int, error)
}
