// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// BackofficeAuthInterface is the contract implemented by *services.BackofficeAuthService and its
// logging / telemetry decorators.
type BackofficeAuthInterface interface {
	ChangePassword(ctx context.Context, id uuid.UUID, currentPassword string, newPassword string) error
	GetByID(ctx context.Context, id uuid.UUID) (*models.BackofficeUser, error)
	Login(ctx context.Context, emailAddr string, password string) (*models.BackofficeUser, string, error)
	ResetPassword(ctx context.Context, id uuid.UUID) error
}
