// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// BackofficeOrganizationInterface is the contract implemented by *services.BackofficeOrganizationService and its
// logging / telemetry decorators.
type BackofficeOrganizationInterface interface {
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*models.Organization, error)
	List(ctx context.Context) ([]models.Organization, error)
	Provision(ctx context.Context, req models.ProvisionOrgRequest) (*models.Organization, *models.User, error)
	ToggleStatus(ctx context.Context, id uuid.UUID, isActive bool) (*models.Organization, error)
	Update(ctx context.Context, id uuid.UUID, req models.OrgDetails) (*models.Organization, error)
}
