// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// BackofficeUserInterface is the contract implemented by *services.BackofficeUserService and its
// logging / telemetry decorators.
type BackofficeUserInterface interface {
	Create(ctx context.Context, req models.CreateBackofficeUserRequest) (*models.BackofficeUser, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*models.BackofficeUser, error)
	List(ctx context.Context) ([]models.BackofficeUser, error)
	Lock(ctx context.Context, id uuid.UUID) error
	ResetPassword(ctx context.Context, id uuid.UUID) error
	Unlock(ctx context.Context, id uuid.UUID) error
	Update(ctx context.Context, id uuid.UUID, req models.UpdateBackofficeUserRequest) (*models.BackofficeUser, error)
}
