// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"
	"time"

	"encoding/json"
	"github.com/google/uuid"

	"lodge-system/internal/models"
	"lodge-system/internal/repository"
)

// BookingInterface is the contract implemented by *services.BookingService and its
// logging / telemetry decorators.
type BookingInterface interface {
	AddAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.CreateAttendeeRequest) (*models.BookingAttendee, error)
	AssignRoom(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.CreateRoomAssignmentRequest) (*models.BookingRoomAssignment, error)
	Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	CancelForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) (uuid.UUID, error)
	CheckIn(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	CheckInAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) error
	CheckOut(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	CheckOutAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) error
	CreateCorporateAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, envelope *models.SubmitAccommodationRequest, matReq *models.MaterialiseRequest) (*models.Booking, error)
	CreateCorporateEvent(ctx context.Context, orgID uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitEventBookingRequest) (*models.Booking, error)
	CreateCorporateMeal(ctx context.Context, orgID uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitMealBookingRequest) (*models.Booking, error)
	CreateFromBooking(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, bookingID uuid.UUID, matReq *models.MaterialiseRequest) (*models.Booking, error)
	CreateIndividual(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.CreateIndividualBookingRequest, metadata json.RawMessage) (*models.Booking, error)
	CreateIndividualEvent(ctx context.Context, orgID uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitEventBookingRequest, metadata json.RawMessage) (*models.Booking, error)
	CreateIndividualMeal(ctx context.Context, orgID uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitMealBookingRequest, metadata json.RawMessage) (*models.Booking, error)
	CreateIndividualRooms(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, promoteID uuid.UUID, webUserID *uuid.UUID, bookerName string, bookerEmail string, bookerPhone string, envelope *models.SubmitIndividualBookingRequest, metadata json.RawMessage) (*models.Booking, error)
	FindOverdueCheckouts(ctx context.Context, orgIDs []uuid.UUID) ([]repository.OverdueBookingRef, error)
	GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Booking, error)
	GetByIDUnscoped(ctx context.Context, id uuid.UUID) (*models.Booking, error)
	GetForApproval(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Booking, error)
	List(ctx context.Context, orgID uuid.UUID, bookerType string, bookingType string, status string, from *time.Time, to *time.Time, page int, pageSize int) ([]models.Booking, int, error)
	ListAssignments(ctx context.Context, id uuid.UUID, orgID uuid.UUID) ([]models.BookingRoomAssignment, error)
	ListAttendees(ctx context.Context, id uuid.UUID, orgID uuid.UUID) ([]models.BookingAttendee, error)
	ListForExport(ctx context.Context, orgID uuid.UUID, bookerType string, bookingType string, status string, from *time.Time, to *time.Time) ([]models.Booking, error)
	ListForWebUser(ctx context.Context, webUserID uuid.UUID, page int, pageSize int) ([]models.Booking, int, error)
	MarkOverstayed(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	RecalculateTotal(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	RemoveAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) error
	RemoveAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, attendeeID uuid.UUID) error
	SetStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, newStatus string, fromStatus string) error
	SubmitPending(ctx context.Context, in *models.PendingBookingInput) (*models.Booking, error)
	UpdateAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID, req *models.UpdateRoomAssignmentRequest) (*models.BookingRoomAssignment, error)
	UpdateAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, attendeeID uuid.UUID, req *models.UpdateAttendeeRequest) (*models.BookingAttendee, error)
	UpdateStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, newStatus string) error
}
