// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// BranchInterface is the contract implemented by *services.BranchService and its
// logging / telemetry decorators.
type BranchInterface interface {
	Create(ctx context.Context, orgID uuid.UUID, req *models.CreateBranchRequest) (*models.Branch, error)
	Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Branch, error)
	List(ctx context.Context, orgID uuid.UUID) ([]models.Branch, error)
	Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateBranchRequest) (*models.Branch, error)
}
