// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// ClientInterface is the contract implemented by *services.ClientService and its
// logging / telemetry decorators.
type ClientInterface interface {
	CreateCorporate(ctx context.Context, orgID uuid.UUID, c *models.CorporateClient) error
	CreateIndividual(ctx context.Context, orgID uuid.UUID, c *models.IndividualClient) error
	DeleteCorporate(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	DeleteIndividual(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	GetCorporateByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorporateClient, error)
	GetCorporateWithBookings(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorporateClientWithBookings, error)
	GetIndividualByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.IndividualClient, error)
	ListCorporate(ctx context.Context, orgID uuid.UUID, search string, status string, page int, pageSize int) ([]models.CorporateClient, int, error)
	ListIndividual(ctx context.Context, orgID uuid.UUID, search string, status string, page int, pageSize int) ([]models.IndividualClient, int, error)
	LookupIndividualByIDNumber(ctx context.Context, orgID uuid.UUID, idNumber string) (*models.IndividualClient, error)
	SearchCorporate(ctx context.Context, orgID uuid.UUID, search string) ([]models.CorporateClient, error)
	UpdateCorporate(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.CorporateClient) (*models.CorporateClient, error)
	UpdateIndividual(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.IndividualClient) (*models.IndividualClient, error)
	UpsertDocuments(ctx context.Context, corporateClientID uuid.UUID, orgID uuid.UUID, urls []string) (*models.BookingDocument, error)
}
