// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// CorProfileInterface is the contract implemented by *services.CorProfileService and its
// logging / telemetry decorators.
type CorProfileInterface interface {
	AddGuest(ctx context.Context, profileID uuid.UUID, req *models.CreateCorporateGuestRequest) (*models.CorporateGuest, error)
	CreateBranch(ctx context.Context, companyID uuid.UUID, req *models.CreateCorBranchRequest) (*models.CorBranchDetails, error)
	CreateProfile(ctx context.Context, orgID uuid.UUID, req *models.CreateCorProfileRequest) (*models.CorProfile, error)
	DeleteGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID) error
	GetBranch(ctx context.Context, id uuid.UUID, companyID uuid.UUID) (*models.CorBranchDetails, error)
	GetCompany(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorCompanyDetails, error)
	GetGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID) (*models.CorporateGuest, error)
	GetProfile(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorProfile, error)
	ListBranches(ctx context.Context, companyID uuid.UUID) ([]models.CorBranchDetails, error)
	ListCompanies(ctx context.Context, orgID uuid.UUID, page int, pageSize int) ([]models.CorCompanyDetails, int, error)
	ListGuests(ctx context.Context, profileID uuid.UUID) ([]models.CorporateGuest, error)
	ListProfiles(ctx context.Context, companyID uuid.UUID, page int, pageSize int) ([]models.CorProfile, int, error)
	ResolveChain(ctx context.Context, orgID uuid.UUID, company models.CorBookingCompanyInput, branch *models.CorBookingBranchInput, profile models.CorBookingProfileInput) (uuid.UUID, *uuid.UUID, uuid.UUID, error)
	UpdateBranch(ctx context.Context, id uuid.UUID, companyID uuid.UUID, req *models.UpdateCorBranchRequest) (*models.CorBranchDetails, error)
	UpdateCompany(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCorCompanyRequest) (*models.CorCompanyDetails, error)
	UpdateGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID, req *models.UpdateCorporateGuestRequest) (*models.CorporateGuest, error)
	UpdateProfile(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCorProfileRequest) (*models.CorProfile, error)
}
