// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// CorporateBookingRequestInterface is the contract implemented by *services.CorporateBookingRequestService and its
// logging / telemetry decorators.
type CorporateBookingRequestInterface interface {
	Approve(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	ApproveFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorporateBookingRequest, error)
	List(ctx context.Context, orgID uuid.UUID, bookingType string, status string, page int, pageSize int) ([]models.CorporateBookingRequest, int, error)
	Reject(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	RejectFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	SubmitAccommodation(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitAccommodationRequest) (*models.Booking, error)
	SubmitEventBooking(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitEventBookingRequest) (*models.Booking, error)
	SubmitMealBooking(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitMealBookingRequest) (*models.Booking, error)
	WalkInAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.SubmitAccommodationRequest, matReq *models.MaterialiseRequest) (*models.Booking, error)
	WalkInEvent(ctx context.Context, orgID uuid.UUID, req *models.SubmitEventBookingRequest) (*models.Booking, error)
	WalkInMeal(ctx context.Context, orgID uuid.UUID, req *models.SubmitMealBookingRequest) (*models.Booking, error)
}
