// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// DashboardInterface is the contract implemented by *services.DashboardService and its
// logging / telemetry decorators.
type DashboardInterface interface {
	GetBookings(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (*models.DashboardBookings, error)
	GetInvoices(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (*models.DashboardInvoices, error)
	GetOrders(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (*models.DashboardOrders, error)
	GetSummary(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (*models.DashboardSummary, error)
}
