// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// GuestAuthInterface is the contract implemented by *services.GuestAuthService and its
// logging / telemetry decorators.
type GuestAuthInterface interface {
	GetByID(ctx context.Context, id uuid.UUID) (*models.Guest, error)
	Login(ctx context.Context, emailAddr string, password string) (*models.Guest, string, error)
	Register(ctx context.Context, req *models.GuestRegisterRequest) (*models.Guest, error)
	ResetPassword(ctx context.Context, emailAddr string) error
	UpdateProfile(ctx context.Context, id uuid.UUID, req *models.GuestUpdateRequest) (*models.Guest, error)
}
