// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// IndividualBookingRequestInterface is the contract implemented by *services.IndividualBookingRequestService and its
// logging / telemetry decorators.
type IndividualBookingRequestInterface interface {
	Approve(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Booking, error)
	ApproveFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	CancelForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.IndividualBookingRequest, error)
	GetForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) (*models.IndividualBookingRequest, error)
	List(ctx context.Context, orgID uuid.UUID, status string, page int, pageSize int) ([]models.IndividualBookingRequest, int, error)
	ListForWebUser(ctx context.Context, webUserID uuid.UUID, page int, pageSize int) ([]models.IndividualBookingRequest, int, error)
	Reject(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	RejectFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	Submit(ctx context.Context, guestID uuid.UUID, req *models.SubmitIndividualBookingRequest) (*models.Booking, error)
	SubmitEvent(ctx context.Context, guestID uuid.UUID, req *models.SubmitEventBookingRequest) (*models.Booking, error)
	SubmitMeal(ctx context.Context, guestID uuid.UUID, req *models.SubmitMealBookingRequest) (*models.Booking, error)
	WalkInAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.SubmitIndividualBookingRequest) (*models.Booking, error)
	WalkInEvent(ctx context.Context, orgID uuid.UUID, req *models.SubmitEventBookingRequest) (*models.Booking, error)
	WalkInMeal(ctx context.Context, orgID uuid.UUID, req *models.SubmitMealBookingRequest) (*models.Booking, error)
}
