// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"
	"time"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// InvoiceInterface is the contract implemented by *services.InvoiceService and its
// logging / telemetry decorators.
type InvoiceInterface interface {
	GenerateForBooking(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) error
	GetByBookingID(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) (*models.Invoice, error)
	GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Invoice, error)
	List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, status string, clientType string, page int, pageSize int) ([]models.Invoice, int, error)
	PostBookingCharge(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID, req *models.PostBookingChargeRequest) (*models.Invoice, error)
	RecalculateRoomCharge(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) error
	RegenerateRoomInvoice(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) error
	SendInvoiceEmail(ctx context.Context, id uuid.UUID, orgID uuid.UUID, pdf []byte) error
	SendPaymentConfirmationEmail(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	UpdateDueDate(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID, dueDate time.Time) error
	UpdateStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateInvoiceStatusRequest) (*models.Invoice, error)
}
