// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// MealCollectionInterface is the contract implemented by *services.MealCollectionService and its
// logging / telemetry decorators.
type MealCollectionInterface interface {
	AssignCard(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.AssignCardRequest) (*models.MealCard, error)
	Collect(ctx context.Context, orgID uuid.UUID, sessionID uuid.UUID, staffID uuid.UUID, staffName string, req *models.MealCollectRequest) (*models.MealCollectionResult, error)
	CreateSession(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.MealSessionCreateRequest) (*models.ResidentMealSession, error)
	DeleteSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	GetCurrentStay(ctx context.Context, orgID uuid.UUID, roomID uuid.UUID) (*models.CurrentStay, error)
	GetSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.ResidentMealSession, error)
	ListCards(ctx context.Context, orgID uuid.UUID, roomID *uuid.UUID, status string) ([]models.MealCard, error)
	ListCollections(ctx context.Context, sessionID uuid.UUID, orgID uuid.UUID) ([]models.MealCollectionLogEntry, error)
	ListSessions(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, status string, mealPeriod string, page int, pageSize int) (*models.PaginatedMealSessions, error)
	ReplaceCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.ReplaceCardRequest) (*models.MealCard, error)
	UpdateCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCardRequest) (*models.MealCard, error)
	UpdateGracePeriod(ctx context.Context, id uuid.UUID, orgID uuid.UUID, minutes int) (*models.ResidentMealSession, error)
	UpdateSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.MealSessionUpdateRequest) (*models.ResidentMealSession, error)
	UpdateSessionStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (*models.ResidentMealSession, error)
	VoidCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.MealCard, error)
}
