// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// MenuInterface is the contract implemented by *services.MenuService and its
// logging / telemetry decorators.
type MenuInterface interface {
	CreateMenuItem(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.CreateMenuItemRequest) (*models.MenuItem, error)
	DeleteMenuItem(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	GetMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, category string, page int, pageSize int) (*models.MenuResponse, error)
	GetMenuItemByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.MenuItem, error)
	GuestGetMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, category string, page int, pageSize int) (*models.MenuResponse, error)
	UpdateMenuItem(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateMenuItemRequest) (*models.MenuItem, error)
	UpsertMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.UpdateMenuRequest, category string, page int, pageSize int) (*models.MenuResponse, error)
}
