// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"
	"time"

	"github.com/google/uuid"

	"lodge-system/internal/models"
	"lodge-system/internal/repository"
)

// OrderInterface is the contract implemented by *services.OrderService and its
// logging / telemetry decorators.
type OrderInterface interface {
	AddItems(ctx context.Context, orderID uuid.UUID, orgID uuid.UUID, req *models.AddOrderItemsRequest) (*models.Order, error)
	CloseAllOrders(ctx context.Context, orgID uuid.UUID) (int64, error)
	GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Order, error)
	List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, orderType string, status string, bookingID *uuid.UUID, from *time.Time, to *time.Time, page int, pageSize int) ([]models.Order, int, error)
	ListCheckedInGuests(ctx context.Context, orgID uuid.UUID) ([]repository.InHouseGuest, error)
	PlaceOrder(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.PlaceOrderRequest) (*models.Order, error)
	PlaceWalkInOrder(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.PlaceWalkInOrderRequest) (*models.Order, error)
	RemoveItem(ctx context.Context, itemID uuid.UUID, orderID uuid.UUID, orgID uuid.UUID) error
	UpdateBarStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (*models.Order, error)
	UpdateKitchenStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (*models.Order, error)
}
