// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// OrganizationSettingsInterface is the contract implemented by *services.OrganizationSettingsService and its
// logging / telemetry decorators.
type OrganizationSettingsInterface interface {
	Get(ctx context.Context, orgID uuid.UUID) (*models.OrganizationSettings, error)
	Upsert(ctx context.Context, orgID uuid.UUID, req *models.UpdateOrganizationSettingsRequest) (*models.OrganizationSettings, error)
}
