// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"
	"time"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// PasswordPolicyInterface is the contract implemented by *services.PasswordPolicyService and its
// logging / telemetry decorators.
type PasswordPolicyInterface interface {
	CalculateLockoutTime(ctx context.Context, orgID ...uuid.UUID) time.Time
	CalculatePasswordExpiry(ctx context.Context, orgID ...uuid.UUID) *time.Time
	CheckAccountLockout(ctx context.Context, user *models.User) (bool, string)
	CheckPasswordExpiry(ctx context.Context, user *models.User) (bool, bool, int)
	GetPolicy(ctx context.Context, orgID ...uuid.UUID) *models.PasswordPolicy
	GetSessionTimeout(ctx context.Context, orgID ...uuid.UUID) int
	LoadGlobalPolicy(ctx context.Context) error
	RecordPasswordChange(ctx context.Context, userID uuid.UUID, passwordHash string) error
	ShouldLockAccount(ctx context.Context, failedAttempts int, orgID ...uuid.UUID) bool
	UpsertPolicy(ctx context.Context, orgID uuid.UUID, req *models.CreatePasswordPolicyRequest) (*models.PasswordPolicy, error)
	ValidateNewPassword(ctx context.Context, userID uuid.UUID, newPassword string, currentPasswordHash string, orgID ...uuid.UUID) error
}
