// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// ReviewInterface is the contract implemented by *services.ReviewService and its
// logging / telemetry decorators.
type ReviewInterface interface {
	GetSummary(ctx context.Context) (*models.RatingSummary, error)
	Submit(ctx context.Context, userID uuid.UUID, req *models.SubmitReviewRequest) (*models.Review, error)
}
