// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// RoleInterface is the contract implemented by *services.RoleService and its
// logging / telemetry decorators.
type RoleInterface interface {
	GetAllRoles(ctx context.Context, orgID uuid.UUID) ([]models.Role, error)
	InitializePredefinedRoles(ctx context.Context) error
}
