// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"
	"time"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// RoomInterface is the contract implemented by *services.RoomService and its
// logging / telemetry decorators.
type RoomInterface interface {
	Create(ctx context.Context, room *models.Room, orgID uuid.UUID) error
	Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Room, error)
	GetByIDUnscoped(ctx context.Context, id uuid.UUID) (*models.Room, error)
	GuestList(ctx context.Context, orgID *uuid.UUID, branchID *uuid.UUID, roomType string, orgName string, isAvailable *bool, page int, pageSize int) ([]models.Room, int, error)
	List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, roomType string, isAvailable *bool, page int, pageSize int) ([]models.Room, int, error)
	ListAvailable(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, checkIn time.Time, checkOut time.Time, roomType string) ([]models.Room, error)
	ListRoomStatus(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) ([]models.RoomStatus, error)
	SetAvailability(ctx context.Context, id uuid.UUID, orgID uuid.UUID, available bool) error
	Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.Room) (*models.Room, error)
	UpdateImages(ctx context.Context, id uuid.UUID, orgID uuid.UUID, images []string) (*models.Room, error)
}
