// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// UserInterface is the contract implemented by *services.UserService and its
// logging / telemetry decorators.
type UserInterface interface {
	ChangePassword(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) error
	ChangeUserRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (*models.User, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	GetAllUsers(ctx context.Context) ([]models.User, error)
	GetByEmail(ctx context.Context, emailAddr string) (*models.User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*models.User, error)
	ListUsers(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, search string, roleID *uuid.UUID, isActive *bool, page int, pageSize int) ([]models.User, int, error)
	LockUser(ctx context.Context, id uuid.UUID) error
	Login(ctx context.Context, emailAddr string, pwd string) (map[string]interface{}, error)
	LoginWithOrg(ctx context.Context, emailAddr string, pwd string, orgID uuid.UUID) (map[string]interface{}, error)
	Register(ctx context.Context, user *models.User) error
	ResetPassword(ctx context.Context, userID uuid.UUID) error
	UnlockUser(ctx context.Context, id uuid.UUID) error
	UpdateUser(ctx context.Context, updates *models.User) (*models.User, error)
	UpdateUserFull(ctx context.Context, id uuid.UUID, callerID uuid.UUID, fullName string, newEmail string, pwd string, roleName string, status string, branchID *uuid.UUID) (*models.User, error)
}
