// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"
	"time"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// VenueInterface is the contract implemented by *services.VenueService and its
// logging / telemetry decorators.
type VenueInterface interface {
	Create(ctx context.Context, venue *models.Venue, orgID uuid.UUID) error
	Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Venue, error)
	GetByIDUnscoped(ctx context.Context, id uuid.UUID) (*models.Venue, error)
	GuestList(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, venueType string, from *time.Time, to *time.Time) ([]models.Venue, error)
	List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, venueType string, isAvailable *bool, from *time.Time, to *time.Time, page int, pageSize int) ([]models.Venue, int, error)
	SetAvailability(ctx context.Context, id uuid.UUID, orgID uuid.UUID, available bool) error
	Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.Venue) (*models.Venue, error)
	UpdateImages(ctx context.Context, id uuid.UUID, orgID uuid.UUID, images []string) (*models.Venue, error)
}
