// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/google/uuid"

	"lodge-system/internal/models"
)

// WebUserAuthInterface is the contract implemented by *services.WebUserAuthService and its
// logging / telemetry decorators.
type WebUserAuthInterface interface {
	ChangePassword(ctx context.Context, id uuid.UUID, oldPassword string, newPassword string) error
	GetByID(ctx context.Context, id uuid.UUID) (*models.WebUser, error)
	Login(ctx context.Context, req *models.WebUserLoginRequest) (*models.WebUser, string, error)
	Register(ctx context.Context, req *models.WebUserRegisterRequest) (*models.WebUser, error)
	Update(ctx context.Context, id uuid.UUID, req *models.WebUserUpdateRequest) (*models.WebUser, error)
}
