// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package interfaces

import (
	"context"

	"lodge-system/internal/models"
)

// WorkflowInterface is the contract implemented by *services.WorkflowService and its
// logging / telemetry decorators.
type WorkflowInterface interface {
	CancelInstance(ctx context.Context, taskID string, orgID string) error
	GetAllOrgTasks(ctx context.Context, orgID string, branchID string, statusFilter string, page int, pageSize int) ([]models.AssignedTask, int, error)
	GetInstanceByTaskID(ctx context.Context, taskID string, orgID string) (*models.WorkflowInstance, error)
	GetInstanceHistory(ctx context.Context, instanceID string, orgID string) ([]models.WorkflowHistory, error)
	GetMyTasks(ctx context.Context, orgID string, userID string, statusFilter string, page int, pageSize int) ([]models.AssignedTask, int, error)
	GetTaskByID(ctx context.Context, taskID string, orgID string) (*models.AssignedTask, error)
	InitiateWorkflow(ctx context.Context, workflowType models.WorkflowType, taskDetails models.TaskDetails, initiatorID string, priority string, dueDate interface{}, orgID string) (*models.WorkflowInstance, error)
	ProcessAction(ctx context.Context, instanceID string, action string, performedByID string, comments string, orgID string) error
}
