// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type AuditLogTelemetryMiddleware struct {
	next interfaces.AuditLogInterface
}

func NewAuditLogTelemetryMiddleware(next interfaces.AuditLogInterface) interfaces.AuditLogInterface {
	return &AuditLogTelemetryMiddleware{next: next}
}

func (m *AuditLogTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID, entityType string, entityID string, action string, from *time.Time, to *time.Time, page int, pageSize int) ([]models.AuditLog, int, error) {
	trace.SpanFromContext(ctx).AddEvent("AuditLog.List")
	return m.next.List(ctx, orgID, entityType, entityID, action, from, to, page, pageSize)
}
