// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type BackofficeUserTelemetryMiddleware struct {
	next interfaces.BackofficeUserInterface
}

func NewBackofficeUserTelemetryMiddleware(next interfaces.BackofficeUserInterface) interfaces.BackofficeUserInterface {
	return &BackofficeUserTelemetryMiddleware{next: next}
}

func (m *BackofficeUserTelemetryMiddleware) Create(ctx context.Context, req models.CreateBackofficeUserRequest) (*models.BackofficeUser, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeUser.Create")
	return m.next.Create(ctx, req)
}

func (m *BackofficeUserTelemetryMiddleware) Delete(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("BackofficeUser.Delete")
	return m.next.Delete(ctx, id)
}

func (m *BackofficeUserTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID) (*models.BackofficeUser, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeUser.GetByID")
	return m.next.GetByID(ctx, id)
}

func (m *BackofficeUserTelemetryMiddleware) List(ctx context.Context) ([]models.BackofficeUser, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeUser.List")
	return m.next.List(ctx)
}

func (m *BackofficeUserTelemetryMiddleware) Lock(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("BackofficeUser.Lock")
	return m.next.Lock(ctx, id)
}

func (m *BackofficeUserTelemetryMiddleware) ResetPassword(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("BackofficeUser.ResetPassword")
	return m.next.ResetPassword(ctx, id)
}

func (m *BackofficeUserTelemetryMiddleware) Unlock(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("BackofficeUser.Unlock")
	return m.next.Unlock(ctx, id)
}

func (m *BackofficeUserTelemetryMiddleware) Update(ctx context.Context, id uuid.UUID, req models.UpdateBackofficeUserRequest) (*models.BackofficeUser, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeUser.Update")
	return m.next.Update(ctx, id, req)
}
