// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type BackofficeOrganizationTelemetryMiddleware struct {
	next interfaces.BackofficeOrganizationInterface
}

func NewBackofficeOrganizationTelemetryMiddleware(next interfaces.BackofficeOrganizationInterface) interfaces.BackofficeOrganizationInterface {
	return &BackofficeOrganizationTelemetryMiddleware{next: next}
}

func (m *BackofficeOrganizationTelemetryMiddleware) Delete(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("BackofficeOrganization.Delete")
	return m.next.Delete(ctx, id)
}

func (m *BackofficeOrganizationTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID) (*models.Organization, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeOrganization.GetByID")
	return m.next.GetByID(ctx, id)
}

func (m *BackofficeOrganizationTelemetryMiddleware) List(ctx context.Context) ([]models.Organization, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeOrganization.List")
	return m.next.List(ctx)
}

func (m *BackofficeOrganizationTelemetryMiddleware) Provision(ctx context.Context, req models.ProvisionOrgRequest) (*models.Organization, *models.User, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeOrganization.Provision")
	return m.next.Provision(ctx, req)
}

func (m *BackofficeOrganizationTelemetryMiddleware) ToggleStatus(ctx context.Context, id uuid.UUID, isActive bool) (*models.Organization, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeOrganization.ToggleStatus")
	return m.next.ToggleStatus(ctx, id, isActive)
}

func (m *BackofficeOrganizationTelemetryMiddleware) Update(ctx context.Context, id uuid.UUID, req models.OrgDetails) (*models.Organization, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeOrganization.Update")
	return m.next.Update(ctx, id, req)
}
