// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type BackofficeAuthTelemetryMiddleware struct {
	next interfaces.BackofficeAuthInterface
}

func NewBackofficeAuthTelemetryMiddleware(next interfaces.BackofficeAuthInterface) interfaces.BackofficeAuthInterface {
	return &BackofficeAuthTelemetryMiddleware{next: next}
}

func (m *BackofficeAuthTelemetryMiddleware) ChangePassword(ctx context.Context, id uuid.UUID, currentPassword string, newPassword string) error {
	trace.SpanFromContext(ctx).AddEvent("BackofficeAuth.ChangePassword")
	return m.next.ChangePassword(ctx, id, currentPassword, newPassword)
}

func (m *BackofficeAuthTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID) (*models.BackofficeUser, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeAuth.GetByID")
	return m.next.GetByID(ctx, id)
}

func (m *BackofficeAuthTelemetryMiddleware) Login(ctx context.Context, emailAddr string, password string) (*models.BackofficeUser, string, error) {
	trace.SpanFromContext(ctx).AddEvent("BackofficeAuth.Login")
	return m.next.Login(ctx, emailAddr, password)
}

func (m *BackofficeAuthTelemetryMiddleware) ResetPassword(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("BackofficeAuth.ResetPassword")
	return m.next.ResetPassword(ctx, id)
}
