// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"
	"time"

	"encoding/json"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
	"lodge-system/internal/repository"
)

type BookingTelemetryMiddleware struct {
	next interfaces.BookingInterface
}

func NewBookingTelemetryMiddleware(next interfaces.BookingInterface) interfaces.BookingInterface {
	return &BookingTelemetryMiddleware{next: next}
}

func (m *BookingTelemetryMiddleware) AddAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.CreateAttendeeRequest) (*models.BookingAttendee, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.AddAttendee")
	return m.next.AddAttendee(ctx, id, orgID, req)
}

func (m *BookingTelemetryMiddleware) AssignRoom(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.CreateRoomAssignmentRequest) (*models.BookingRoomAssignment, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.AssignRoom")
	return m.next.AssignRoom(ctx, id, orgID, req)
}

func (m *BookingTelemetryMiddleware) Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.Cancel")
	return m.next.Cancel(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) CancelForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) (uuid.UUID, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CancelForWebUser")
	return m.next.CancelForWebUser(ctx, id, webUserID)
}

func (m *BookingTelemetryMiddleware) CheckIn(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.CheckIn")
	return m.next.CheckIn(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) CheckInAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.CheckInAssignment")
	return m.next.CheckInAssignment(ctx, id, orgID, assignmentID)
}

func (m *BookingTelemetryMiddleware) CheckOut(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.CheckOut")
	return m.next.CheckOut(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) CheckOutAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.CheckOutAssignment")
	return m.next.CheckOutAssignment(ctx, id, orgID, assignmentID)
}

func (m *BookingTelemetryMiddleware) CreateCorporateAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, envelope *models.SubmitAccommodationRequest, matReq *models.MaterialiseRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CreateCorporateAccommodation")
	return m.next.CreateCorporateAccommodation(ctx, orgID, branchID, corProfileID, companyID, envelope, matReq)
}

func (m *BookingTelemetryMiddleware) CreateCorporateEvent(ctx context.Context, orgID uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitEventBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CreateCorporateEvent")
	return m.next.CreateCorporateEvent(ctx, orgID, corProfileID, companyID, webUserID, promoteID, envelope)
}

func (m *BookingTelemetryMiddleware) CreateCorporateMeal(ctx context.Context, orgID uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitMealBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CreateCorporateMeal")
	return m.next.CreateCorporateMeal(ctx, orgID, corProfileID, companyID, webUserID, promoteID, envelope)
}

func (m *BookingTelemetryMiddleware) CreateFromBooking(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, bookingID uuid.UUID, matReq *models.MaterialiseRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CreateFromBooking")
	return m.next.CreateFromBooking(ctx, orgID, branchID, bookingID, matReq)
}

func (m *BookingTelemetryMiddleware) CreateIndividual(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.CreateIndividualBookingRequest, metadata json.RawMessage) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CreateIndividual")
	return m.next.CreateIndividual(ctx, orgID, branchID, req, metadata)
}

func (m *BookingTelemetryMiddleware) CreateIndividualEvent(ctx context.Context, orgID uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitEventBookingRequest, metadata json.RawMessage) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CreateIndividualEvent")
	return m.next.CreateIndividualEvent(ctx, orgID, webUserID, promoteID, envelope, metadata)
}

func (m *BookingTelemetryMiddleware) CreateIndividualMeal(ctx context.Context, orgID uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitMealBookingRequest, metadata json.RawMessage) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CreateIndividualMeal")
	return m.next.CreateIndividualMeal(ctx, orgID, webUserID, promoteID, envelope, metadata)
}

func (m *BookingTelemetryMiddleware) CreateIndividualRooms(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, promoteID uuid.UUID, webUserID *uuid.UUID, bookerName string, bookerEmail string, bookerPhone string, envelope *models.SubmitIndividualBookingRequest, metadata json.RawMessage) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.CreateIndividualRooms")
	return m.next.CreateIndividualRooms(ctx, orgID, branchID, promoteID, webUserID, bookerName, bookerEmail, bookerPhone, envelope, metadata)
}

func (m *BookingTelemetryMiddleware) FindOverdueCheckouts(ctx context.Context, orgIDs []uuid.UUID) ([]repository.OverdueBookingRef, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.FindOverdueCheckouts")
	return m.next.FindOverdueCheckouts(ctx, orgIDs)
}

func (m *BookingTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.GetByID")
	return m.next.GetByID(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) GetByIDUnscoped(ctx context.Context, id uuid.UUID) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.GetByIDUnscoped")
	return m.next.GetByIDUnscoped(ctx, id)
}

func (m *BookingTelemetryMiddleware) GetForApproval(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.GetForApproval")
	return m.next.GetForApproval(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID, bookerType string, bookingType string, status string, from *time.Time, to *time.Time, page int, pageSize int) ([]models.Booking, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.List")
	return m.next.List(ctx, orgID, bookerType, bookingType, status, from, to, page, pageSize)
}

func (m *BookingTelemetryMiddleware) ListAssignments(ctx context.Context, id uuid.UUID, orgID uuid.UUID) ([]models.BookingRoomAssignment, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.ListAssignments")
	return m.next.ListAssignments(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) ListAttendees(ctx context.Context, id uuid.UUID, orgID uuid.UUID) ([]models.BookingAttendee, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.ListAttendees")
	return m.next.ListAttendees(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) ListForExport(ctx context.Context, orgID uuid.UUID, bookerType string, bookingType string, status string, from *time.Time, to *time.Time) ([]models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.ListForExport")
	return m.next.ListForExport(ctx, orgID, bookerType, bookingType, status, from, to)
}

func (m *BookingTelemetryMiddleware) ListForWebUser(ctx context.Context, webUserID uuid.UUID, page int, pageSize int) ([]models.Booking, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.ListForWebUser")
	return m.next.ListForWebUser(ctx, webUserID, page, pageSize)
}

func (m *BookingTelemetryMiddleware) MarkOverstayed(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.MarkOverstayed")
	return m.next.MarkOverstayed(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) RecalculateTotal(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.RecalculateTotal")
	return m.next.RecalculateTotal(ctx, id, orgID)
}

func (m *BookingTelemetryMiddleware) RemoveAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.RemoveAssignment")
	return m.next.RemoveAssignment(ctx, id, orgID, assignmentID)
}

func (m *BookingTelemetryMiddleware) RemoveAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, attendeeID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.RemoveAttendee")
	return m.next.RemoveAttendee(ctx, id, orgID, attendeeID)
}

func (m *BookingTelemetryMiddleware) SetStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, newStatus string, fromStatus string) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.SetStatus")
	return m.next.SetStatus(ctx, id, orgID, newStatus, fromStatus)
}

func (m *BookingTelemetryMiddleware) SubmitPending(ctx context.Context, in *models.PendingBookingInput) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.SubmitPending")
	return m.next.SubmitPending(ctx, in)
}

func (m *BookingTelemetryMiddleware) UpdateAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID, req *models.UpdateRoomAssignmentRequest) (*models.BookingRoomAssignment, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.UpdateAssignment")
	return m.next.UpdateAssignment(ctx, id, orgID, assignmentID, req)
}

func (m *BookingTelemetryMiddleware) UpdateAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, attendeeID uuid.UUID, req *models.UpdateAttendeeRequest) (*models.BookingAttendee, error) {
	trace.SpanFromContext(ctx).AddEvent("Booking.UpdateAttendee")
	return m.next.UpdateAttendee(ctx, id, orgID, attendeeID, req)
}

func (m *BookingTelemetryMiddleware) UpdateStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, newStatus string) error {
	trace.SpanFromContext(ctx).AddEvent("Booking.UpdateStatus")
	return m.next.UpdateStatus(ctx, id, orgID, newStatus)
}
