// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type BranchTelemetryMiddleware struct {
	next interfaces.BranchInterface
}

func NewBranchTelemetryMiddleware(next interfaces.BranchInterface) interfaces.BranchInterface {
	return &BranchTelemetryMiddleware{next: next}
}

func (m *BranchTelemetryMiddleware) Create(ctx context.Context, orgID uuid.UUID, req *models.CreateBranchRequest) (*models.Branch, error) {
	trace.SpanFromContext(ctx).AddEvent("Branch.Create")
	return m.next.Create(ctx, orgID, req)
}

func (m *BranchTelemetryMiddleware) Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Branch.Delete")
	return m.next.Delete(ctx, id, orgID)
}

func (m *BranchTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Branch, error) {
	trace.SpanFromContext(ctx).AddEvent("Branch.GetByID")
	return m.next.GetByID(ctx, id, orgID)
}

func (m *BranchTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID) ([]models.Branch, error) {
	trace.SpanFromContext(ctx).AddEvent("Branch.List")
	return m.next.List(ctx, orgID)
}

func (m *BranchTelemetryMiddleware) Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateBranchRequest) (*models.Branch, error) {
	trace.SpanFromContext(ctx).AddEvent("Branch.Update")
	return m.next.Update(ctx, id, orgID, req)
}
