// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type ClientTelemetryMiddleware struct {
	next interfaces.ClientInterface
}

func NewClientTelemetryMiddleware(next interfaces.ClientInterface) interfaces.ClientInterface {
	return &ClientTelemetryMiddleware{next: next}
}

func (m *ClientTelemetryMiddleware) CreateCorporate(ctx context.Context, orgID uuid.UUID, c *models.CorporateClient) error {
	trace.SpanFromContext(ctx).AddEvent("Client.CreateCorporate")
	return m.next.CreateCorporate(ctx, orgID, c)
}

func (m *ClientTelemetryMiddleware) CreateIndividual(ctx context.Context, orgID uuid.UUID, c *models.IndividualClient) error {
	trace.SpanFromContext(ctx).AddEvent("Client.CreateIndividual")
	return m.next.CreateIndividual(ctx, orgID, c)
}

func (m *ClientTelemetryMiddleware) DeleteCorporate(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Client.DeleteCorporate")
	return m.next.DeleteCorporate(ctx, id, orgID)
}

func (m *ClientTelemetryMiddleware) DeleteIndividual(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Client.DeleteIndividual")
	return m.next.DeleteIndividual(ctx, id, orgID)
}

func (m *ClientTelemetryMiddleware) GetCorporateByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorporateClient, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.GetCorporateByID")
	return m.next.GetCorporateByID(ctx, id, orgID)
}

func (m *ClientTelemetryMiddleware) GetCorporateWithBookings(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorporateClientWithBookings, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.GetCorporateWithBookings")
	return m.next.GetCorporateWithBookings(ctx, id, orgID)
}

func (m *ClientTelemetryMiddleware) GetIndividualByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.IndividualClient, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.GetIndividualByID")
	return m.next.GetIndividualByID(ctx, id, orgID)
}

func (m *ClientTelemetryMiddleware) ListCorporate(ctx context.Context, orgID uuid.UUID, search string, status string, page int, pageSize int) ([]models.CorporateClient, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.ListCorporate")
	return m.next.ListCorporate(ctx, orgID, search, status, page, pageSize)
}

func (m *ClientTelemetryMiddleware) ListIndividual(ctx context.Context, orgID uuid.UUID, search string, status string, page int, pageSize int) ([]models.IndividualClient, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.ListIndividual")
	return m.next.ListIndividual(ctx, orgID, search, status, page, pageSize)
}

func (m *ClientTelemetryMiddleware) LookupIndividualByIDNumber(ctx context.Context, orgID uuid.UUID, idNumber string) (*models.IndividualClient, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.LookupIndividualByIDNumber")
	return m.next.LookupIndividualByIDNumber(ctx, orgID, idNumber)
}

func (m *ClientTelemetryMiddleware) SearchCorporate(ctx context.Context, orgID uuid.UUID, search string) ([]models.CorporateClient, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.SearchCorporate")
	return m.next.SearchCorporate(ctx, orgID, search)
}

func (m *ClientTelemetryMiddleware) UpdateCorporate(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.CorporateClient) (*models.CorporateClient, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.UpdateCorporate")
	return m.next.UpdateCorporate(ctx, id, orgID, updates)
}

func (m *ClientTelemetryMiddleware) UpdateIndividual(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.IndividualClient) (*models.IndividualClient, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.UpdateIndividual")
	return m.next.UpdateIndividual(ctx, id, orgID, updates)
}

func (m *ClientTelemetryMiddleware) UpsertDocuments(ctx context.Context, corporateClientID uuid.UUID, orgID uuid.UUID, urls []string) (*models.BookingDocument, error) {
	trace.SpanFromContext(ctx).AddEvent("Client.UpsertDocuments")
	return m.next.UpsertDocuments(ctx, corporateClientID, orgID, urls)
}
