// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type CorProfileTelemetryMiddleware struct {
	next interfaces.CorProfileInterface
}

func NewCorProfileTelemetryMiddleware(next interfaces.CorProfileInterface) interfaces.CorProfileInterface {
	return &CorProfileTelemetryMiddleware{next: next}
}

func (m *CorProfileTelemetryMiddleware) AddGuest(ctx context.Context, profileID uuid.UUID, req *models.CreateCorporateGuestRequest) (*models.CorporateGuest, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.AddGuest")
	return m.next.AddGuest(ctx, profileID, req)
}

func (m *CorProfileTelemetryMiddleware) CreateBranch(ctx context.Context, companyID uuid.UUID, req *models.CreateCorBranchRequest) (*models.CorBranchDetails, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.CreateBranch")
	return m.next.CreateBranch(ctx, companyID, req)
}

func (m *CorProfileTelemetryMiddleware) CreateProfile(ctx context.Context, orgID uuid.UUID, req *models.CreateCorProfileRequest) (*models.CorProfile, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.CreateProfile")
	return m.next.CreateProfile(ctx, orgID, req)
}

func (m *CorProfileTelemetryMiddleware) DeleteGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.DeleteGuest")
	return m.next.DeleteGuest(ctx, id, profileID)
}

func (m *CorProfileTelemetryMiddleware) GetBranch(ctx context.Context, id uuid.UUID, companyID uuid.UUID) (*models.CorBranchDetails, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.GetBranch")
	return m.next.GetBranch(ctx, id, companyID)
}

func (m *CorProfileTelemetryMiddleware) GetCompany(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorCompanyDetails, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.GetCompany")
	return m.next.GetCompany(ctx, id, orgID)
}

func (m *CorProfileTelemetryMiddleware) GetGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID) (*models.CorporateGuest, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.GetGuest")
	return m.next.GetGuest(ctx, id, profileID)
}

func (m *CorProfileTelemetryMiddleware) GetProfile(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorProfile, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.GetProfile")
	return m.next.GetProfile(ctx, id, orgID)
}

func (m *CorProfileTelemetryMiddleware) ListBranches(ctx context.Context, companyID uuid.UUID) ([]models.CorBranchDetails, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.ListBranches")
	return m.next.ListBranches(ctx, companyID)
}

func (m *CorProfileTelemetryMiddleware) ListCompanies(ctx context.Context, orgID uuid.UUID, page int, pageSize int) ([]models.CorCompanyDetails, int, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.ListCompanies")
	return m.next.ListCompanies(ctx, orgID, page, pageSize)
}

func (m *CorProfileTelemetryMiddleware) ListGuests(ctx context.Context, profileID uuid.UUID) ([]models.CorporateGuest, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.ListGuests")
	return m.next.ListGuests(ctx, profileID)
}

func (m *CorProfileTelemetryMiddleware) ListProfiles(ctx context.Context, companyID uuid.UUID, page int, pageSize int) ([]models.CorProfile, int, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.ListProfiles")
	return m.next.ListProfiles(ctx, companyID, page, pageSize)
}

func (m *CorProfileTelemetryMiddleware) ResolveChain(ctx context.Context, orgID uuid.UUID, company models.CorBookingCompanyInput, branch *models.CorBookingBranchInput, profile models.CorBookingProfileInput) (uuid.UUID, *uuid.UUID, uuid.UUID, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.ResolveChain")
	return m.next.ResolveChain(ctx, orgID, company, branch, profile)
}

func (m *CorProfileTelemetryMiddleware) UpdateBranch(ctx context.Context, id uuid.UUID, companyID uuid.UUID, req *models.UpdateCorBranchRequest) (*models.CorBranchDetails, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.UpdateBranch")
	return m.next.UpdateBranch(ctx, id, companyID, req)
}

func (m *CorProfileTelemetryMiddleware) UpdateCompany(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCorCompanyRequest) (*models.CorCompanyDetails, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.UpdateCompany")
	return m.next.UpdateCompany(ctx, id, orgID, req)
}

func (m *CorProfileTelemetryMiddleware) UpdateGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID, req *models.UpdateCorporateGuestRequest) (*models.CorporateGuest, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.UpdateGuest")
	return m.next.UpdateGuest(ctx, id, profileID, req)
}

func (m *CorProfileTelemetryMiddleware) UpdateProfile(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCorProfileRequest) (*models.CorProfile, error) {
	trace.SpanFromContext(ctx).AddEvent("CorProfile.UpdateProfile")
	return m.next.UpdateProfile(ctx, id, orgID, req)
}
