// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type CorporateBookingRequestTelemetryMiddleware struct {
	next interfaces.CorporateBookingRequestInterface
}

func NewCorporateBookingRequestTelemetryMiddleware(next interfaces.CorporateBookingRequestInterface) interfaces.CorporateBookingRequestInterface {
	return &CorporateBookingRequestTelemetryMiddleware{next: next}
}

func (m *CorporateBookingRequestTelemetryMiddleware) Approve(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.Approve")
	return m.next.Approve(ctx, id, orgID)
}

func (m *CorporateBookingRequestTelemetryMiddleware) ApproveFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.ApproveFromWorkflow")
	return m.next.ApproveFromWorkflow(ctx, id, orgID)
}

func (m *CorporateBookingRequestTelemetryMiddleware) Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.Cancel")
	return m.next.Cancel(ctx, id, orgID)
}

func (m *CorporateBookingRequestTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.CorporateBookingRequest, error) {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.GetByID")
	return m.next.GetByID(ctx, id, orgID)
}

func (m *CorporateBookingRequestTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID, bookingType string, status string, page int, pageSize int) ([]models.CorporateBookingRequest, int, error) {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.List")
	return m.next.List(ctx, orgID, bookingType, status, page, pageSize)
}

func (m *CorporateBookingRequestTelemetryMiddleware) Reject(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.Reject")
	return m.next.Reject(ctx, id, orgID)
}

func (m *CorporateBookingRequestTelemetryMiddleware) RejectFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.RejectFromWorkflow")
	return m.next.RejectFromWorkflow(ctx, id, orgID)
}

func (m *CorporateBookingRequestTelemetryMiddleware) SubmitAccommodation(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitAccommodationRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.SubmitAccommodation")
	return m.next.SubmitAccommodation(ctx, orgID, webUserID, req)
}

func (m *CorporateBookingRequestTelemetryMiddleware) SubmitEventBooking(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitEventBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.SubmitEventBooking")
	return m.next.SubmitEventBooking(ctx, orgID, webUserID, req)
}

func (m *CorporateBookingRequestTelemetryMiddleware) SubmitMealBooking(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitMealBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.SubmitMealBooking")
	return m.next.SubmitMealBooking(ctx, orgID, webUserID, req)
}

func (m *CorporateBookingRequestTelemetryMiddleware) WalkInAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.SubmitAccommodationRequest, matReq *models.MaterialiseRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.WalkInAccommodation")
	return m.next.WalkInAccommodation(ctx, orgID, branchID, req, matReq)
}

func (m *CorporateBookingRequestTelemetryMiddleware) WalkInEvent(ctx context.Context, orgID uuid.UUID, req *models.SubmitEventBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.WalkInEvent")
	return m.next.WalkInEvent(ctx, orgID, req)
}

func (m *CorporateBookingRequestTelemetryMiddleware) WalkInMeal(ctx context.Context, orgID uuid.UUID, req *models.SubmitMealBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("CorporateBookingRequest.WalkInMeal")
	return m.next.WalkInMeal(ctx, orgID, req)
}
