// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type DashboardTelemetryMiddleware struct {
	next interfaces.DashboardInterface
}

func NewDashboardTelemetryMiddleware(next interfaces.DashboardInterface) interfaces.DashboardInterface {
	return &DashboardTelemetryMiddleware{next: next}
}

func (m *DashboardTelemetryMiddleware) GetBookings(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (*models.DashboardBookings, error) {
	trace.SpanFromContext(ctx).AddEvent("Dashboard.GetBookings")
	return m.next.GetBookings(ctx, orgID, branchID)
}

func (m *DashboardTelemetryMiddleware) GetInvoices(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (*models.DashboardInvoices, error) {
	trace.SpanFromContext(ctx).AddEvent("Dashboard.GetInvoices")
	return m.next.GetInvoices(ctx, orgID, branchID)
}

func (m *DashboardTelemetryMiddleware) GetOrders(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (*models.DashboardOrders, error) {
	trace.SpanFromContext(ctx).AddEvent("Dashboard.GetOrders")
	return m.next.GetOrders(ctx, orgID, branchID)
}

func (m *DashboardTelemetryMiddleware) GetSummary(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (*models.DashboardSummary, error) {
	trace.SpanFromContext(ctx).AddEvent("Dashboard.GetSummary")
	return m.next.GetSummary(ctx, orgID, branchID)
}
