// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type GuestAuthTelemetryMiddleware struct {
	next interfaces.GuestAuthInterface
}

func NewGuestAuthTelemetryMiddleware(next interfaces.GuestAuthInterface) interfaces.GuestAuthInterface {
	return &GuestAuthTelemetryMiddleware{next: next}
}

func (m *GuestAuthTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID) (*models.Guest, error) {
	trace.SpanFromContext(ctx).AddEvent("GuestAuth.GetByID")
	return m.next.GetByID(ctx, id)
}

func (m *GuestAuthTelemetryMiddleware) Login(ctx context.Context, emailAddr string, password string) (*models.Guest, string, error) {
	trace.SpanFromContext(ctx).AddEvent("GuestAuth.Login")
	return m.next.Login(ctx, emailAddr, password)
}

func (m *GuestAuthTelemetryMiddleware) Register(ctx context.Context, req *models.GuestRegisterRequest) (*models.Guest, error) {
	trace.SpanFromContext(ctx).AddEvent("GuestAuth.Register")
	return m.next.Register(ctx, req)
}

func (m *GuestAuthTelemetryMiddleware) ResetPassword(ctx context.Context, emailAddr string) error {
	trace.SpanFromContext(ctx).AddEvent("GuestAuth.ResetPassword")
	return m.next.ResetPassword(ctx, emailAddr)
}

func (m *GuestAuthTelemetryMiddleware) UpdateProfile(ctx context.Context, id uuid.UUID, req *models.GuestUpdateRequest) (*models.Guest, error) {
	trace.SpanFromContext(ctx).AddEvent("GuestAuth.UpdateProfile")
	return m.next.UpdateProfile(ctx, id, req)
}
