// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type IndividualBookingRequestTelemetryMiddleware struct {
	next interfaces.IndividualBookingRequestInterface
}

func NewIndividualBookingRequestTelemetryMiddleware(next interfaces.IndividualBookingRequestInterface) interfaces.IndividualBookingRequestInterface {
	return &IndividualBookingRequestTelemetryMiddleware{next: next}
}

func (m *IndividualBookingRequestTelemetryMiddleware) Approve(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.Approve")
	return m.next.Approve(ctx, id, orgID)
}

func (m *IndividualBookingRequestTelemetryMiddleware) ApproveFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.ApproveFromWorkflow")
	return m.next.ApproveFromWorkflow(ctx, id, orgID)
}

func (m *IndividualBookingRequestTelemetryMiddleware) Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.Cancel")
	return m.next.Cancel(ctx, id, orgID)
}

func (m *IndividualBookingRequestTelemetryMiddleware) CancelForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.CancelForWebUser")
	return m.next.CancelForWebUser(ctx, id, webUserID)
}

func (m *IndividualBookingRequestTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.IndividualBookingRequest, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.GetByID")
	return m.next.GetByID(ctx, id, orgID)
}

func (m *IndividualBookingRequestTelemetryMiddleware) GetForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) (*models.IndividualBookingRequest, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.GetForWebUser")
	return m.next.GetForWebUser(ctx, id, webUserID)
}

func (m *IndividualBookingRequestTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID, status string, page int, pageSize int) ([]models.IndividualBookingRequest, int, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.List")
	return m.next.List(ctx, orgID, status, page, pageSize)
}

func (m *IndividualBookingRequestTelemetryMiddleware) ListForWebUser(ctx context.Context, webUserID uuid.UUID, page int, pageSize int) ([]models.IndividualBookingRequest, int, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.ListForWebUser")
	return m.next.ListForWebUser(ctx, webUserID, page, pageSize)
}

func (m *IndividualBookingRequestTelemetryMiddleware) Reject(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.Reject")
	return m.next.Reject(ctx, id, orgID)
}

func (m *IndividualBookingRequestTelemetryMiddleware) RejectFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.RejectFromWorkflow")
	return m.next.RejectFromWorkflow(ctx, id, orgID)
}

func (m *IndividualBookingRequestTelemetryMiddleware) Submit(ctx context.Context, guestID uuid.UUID, req *models.SubmitIndividualBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.Submit")
	return m.next.Submit(ctx, guestID, req)
}

func (m *IndividualBookingRequestTelemetryMiddleware) SubmitEvent(ctx context.Context, guestID uuid.UUID, req *models.SubmitEventBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.SubmitEvent")
	return m.next.SubmitEvent(ctx, guestID, req)
}

func (m *IndividualBookingRequestTelemetryMiddleware) SubmitMeal(ctx context.Context, guestID uuid.UUID, req *models.SubmitMealBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.SubmitMeal")
	return m.next.SubmitMeal(ctx, guestID, req)
}

func (m *IndividualBookingRequestTelemetryMiddleware) WalkInAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.SubmitIndividualBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.WalkInAccommodation")
	return m.next.WalkInAccommodation(ctx, orgID, branchID, req)
}

func (m *IndividualBookingRequestTelemetryMiddleware) WalkInEvent(ctx context.Context, orgID uuid.UUID, req *models.SubmitEventBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.WalkInEvent")
	return m.next.WalkInEvent(ctx, orgID, req)
}

func (m *IndividualBookingRequestTelemetryMiddleware) WalkInMeal(ctx context.Context, orgID uuid.UUID, req *models.SubmitMealBookingRequest) (*models.Booking, error) {
	trace.SpanFromContext(ctx).AddEvent("IndividualBookingRequest.WalkInMeal")
	return m.next.WalkInMeal(ctx, orgID, req)
}
