// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type InvoiceTelemetryMiddleware struct {
	next interfaces.InvoiceInterface
}

func NewInvoiceTelemetryMiddleware(next interfaces.InvoiceInterface) interfaces.InvoiceInterface {
	return &InvoiceTelemetryMiddleware{next: next}
}

func (m *InvoiceTelemetryMiddleware) GenerateForBooking(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Invoice.GenerateForBooking")
	return m.next.GenerateForBooking(ctx, bookingID, orgID)
}

func (m *InvoiceTelemetryMiddleware) GetByBookingID(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) (*models.Invoice, error) {
	trace.SpanFromContext(ctx).AddEvent("Invoice.GetByBookingID")
	return m.next.GetByBookingID(ctx, bookingID, orgID)
}

func (m *InvoiceTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Invoice, error) {
	trace.SpanFromContext(ctx).AddEvent("Invoice.GetByID")
	return m.next.GetByID(ctx, id, orgID)
}

func (m *InvoiceTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, status string, clientType string, page int, pageSize int) ([]models.Invoice, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Invoice.List")
	return m.next.List(ctx, orgID, branchID, status, clientType, page, pageSize)
}

func (m *InvoiceTelemetryMiddleware) PostBookingCharge(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID, req *models.PostBookingChargeRequest) (*models.Invoice, error) {
	trace.SpanFromContext(ctx).AddEvent("Invoice.PostBookingCharge")
	return m.next.PostBookingCharge(ctx, bookingID, orgID, req)
}

func (m *InvoiceTelemetryMiddleware) RecalculateRoomCharge(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Invoice.RecalculateRoomCharge")
	return m.next.RecalculateRoomCharge(ctx, bookingID, orgID)
}

func (m *InvoiceTelemetryMiddleware) RegenerateRoomInvoice(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Invoice.RegenerateRoomInvoice")
	return m.next.RegenerateRoomInvoice(ctx, bookingID, orgID)
}

func (m *InvoiceTelemetryMiddleware) SendInvoiceEmail(ctx context.Context, id uuid.UUID, orgID uuid.UUID, pdf []byte) error {
	trace.SpanFromContext(ctx).AddEvent("Invoice.SendInvoiceEmail")
	return m.next.SendInvoiceEmail(ctx, id, orgID, pdf)
}

func (m *InvoiceTelemetryMiddleware) SendPaymentConfirmationEmail(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Invoice.SendPaymentConfirmationEmail")
	return m.next.SendPaymentConfirmationEmail(ctx, id, orgID)
}

func (m *InvoiceTelemetryMiddleware) UpdateDueDate(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID, dueDate time.Time) error {
	trace.SpanFromContext(ctx).AddEvent("Invoice.UpdateDueDate")
	return m.next.UpdateDueDate(ctx, bookingID, orgID, dueDate)
}

func (m *InvoiceTelemetryMiddleware) UpdateStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateInvoiceStatusRequest) (*models.Invoice, error) {
	trace.SpanFromContext(ctx).AddEvent("Invoice.UpdateStatus")
	return m.next.UpdateStatus(ctx, id, orgID, req)
}
