// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type MealCollectionTelemetryMiddleware struct {
	next interfaces.MealCollectionInterface
}

func NewMealCollectionTelemetryMiddleware(next interfaces.MealCollectionInterface) interfaces.MealCollectionInterface {
	return &MealCollectionTelemetryMiddleware{next: next}
}

func (m *MealCollectionTelemetryMiddleware) AssignCard(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.AssignCardRequest) (*models.MealCard, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.AssignCard")
	return m.next.AssignCard(ctx, orgID, branchID, req)
}

func (m *MealCollectionTelemetryMiddleware) Collect(ctx context.Context, orgID uuid.UUID, sessionID uuid.UUID, staffID uuid.UUID, staffName string, req *models.MealCollectRequest) (*models.MealCollectionResult, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.Collect")
	return m.next.Collect(ctx, orgID, sessionID, staffID, staffName, req)
}

func (m *MealCollectionTelemetryMiddleware) CreateSession(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.MealSessionCreateRequest) (*models.ResidentMealSession, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.CreateSession")
	return m.next.CreateSession(ctx, orgID, branchID, req)
}

func (m *MealCollectionTelemetryMiddleware) DeleteSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.DeleteSession")
	return m.next.DeleteSession(ctx, id, orgID)
}

func (m *MealCollectionTelemetryMiddleware) GetCurrentStay(ctx context.Context, orgID uuid.UUID, roomID uuid.UUID) (*models.CurrentStay, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.GetCurrentStay")
	return m.next.GetCurrentStay(ctx, orgID, roomID)
}

func (m *MealCollectionTelemetryMiddleware) GetSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.ResidentMealSession, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.GetSession")
	return m.next.GetSession(ctx, id, orgID)
}

func (m *MealCollectionTelemetryMiddleware) ListCards(ctx context.Context, orgID uuid.UUID, roomID *uuid.UUID, status string) ([]models.MealCard, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.ListCards")
	return m.next.ListCards(ctx, orgID, roomID, status)
}

func (m *MealCollectionTelemetryMiddleware) ListCollections(ctx context.Context, sessionID uuid.UUID, orgID uuid.UUID) ([]models.MealCollectionLogEntry, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.ListCollections")
	return m.next.ListCollections(ctx, sessionID, orgID)
}

func (m *MealCollectionTelemetryMiddleware) ListSessions(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, status string, mealPeriod string, page int, pageSize int) (*models.PaginatedMealSessions, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.ListSessions")
	return m.next.ListSessions(ctx, orgID, branchID, status, mealPeriod, page, pageSize)
}

func (m *MealCollectionTelemetryMiddleware) ReplaceCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.ReplaceCardRequest) (*models.MealCard, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.ReplaceCard")
	return m.next.ReplaceCard(ctx, id, orgID, req)
}

func (m *MealCollectionTelemetryMiddleware) UpdateCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCardRequest) (*models.MealCard, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.UpdateCard")
	return m.next.UpdateCard(ctx, id, orgID, req)
}

func (m *MealCollectionTelemetryMiddleware) UpdateGracePeriod(ctx context.Context, id uuid.UUID, orgID uuid.UUID, minutes int) (*models.ResidentMealSession, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.UpdateGracePeriod")
	return m.next.UpdateGracePeriod(ctx, id, orgID, minutes)
}

func (m *MealCollectionTelemetryMiddleware) UpdateSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.MealSessionUpdateRequest) (*models.ResidentMealSession, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.UpdateSession")
	return m.next.UpdateSession(ctx, id, orgID, req)
}

func (m *MealCollectionTelemetryMiddleware) UpdateSessionStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (*models.ResidentMealSession, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.UpdateSessionStatus")
	return m.next.UpdateSessionStatus(ctx, id, orgID, status)
}

func (m *MealCollectionTelemetryMiddleware) VoidCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.MealCard, error) {
	trace.SpanFromContext(ctx).AddEvent("MealCollection.VoidCard")
	return m.next.VoidCard(ctx, id, orgID)
}
