// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type MenuTelemetryMiddleware struct {
	next interfaces.MenuInterface
}

func NewMenuTelemetryMiddleware(next interfaces.MenuInterface) interfaces.MenuInterface {
	return &MenuTelemetryMiddleware{next: next}
}

func (m *MenuTelemetryMiddleware) CreateMenuItem(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.CreateMenuItemRequest) (*models.MenuItem, error) {
	trace.SpanFromContext(ctx).AddEvent("Menu.CreateMenuItem")
	return m.next.CreateMenuItem(ctx, orgID, branchID, req)
}

func (m *MenuTelemetryMiddleware) DeleteMenuItem(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Menu.DeleteMenuItem")
	return m.next.DeleteMenuItem(ctx, id, orgID)
}

func (m *MenuTelemetryMiddleware) GetMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, category string, page int, pageSize int) (*models.MenuResponse, error) {
	trace.SpanFromContext(ctx).AddEvent("Menu.GetMenu")
	return m.next.GetMenu(ctx, orgID, branchID, category, page, pageSize)
}

func (m *MenuTelemetryMiddleware) GetMenuItemByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.MenuItem, error) {
	trace.SpanFromContext(ctx).AddEvent("Menu.GetMenuItemByID")
	return m.next.GetMenuItemByID(ctx, id, orgID)
}

func (m *MenuTelemetryMiddleware) GuestGetMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, category string, page int, pageSize int) (*models.MenuResponse, error) {
	trace.SpanFromContext(ctx).AddEvent("Menu.GuestGetMenu")
	return m.next.GuestGetMenu(ctx, orgID, branchID, category, page, pageSize)
}

func (m *MenuTelemetryMiddleware) UpdateMenuItem(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateMenuItemRequest) (*models.MenuItem, error) {
	trace.SpanFromContext(ctx).AddEvent("Menu.UpdateMenuItem")
	return m.next.UpdateMenuItem(ctx, id, orgID, req)
}

func (m *MenuTelemetryMiddleware) UpsertMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.UpdateMenuRequest, category string, page int, pageSize int) (*models.MenuResponse, error) {
	trace.SpanFromContext(ctx).AddEvent("Menu.UpsertMenu")
	return m.next.UpsertMenu(ctx, orgID, branchID, req, category, page, pageSize)
}
