// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
	"lodge-system/internal/repository"
)

type OrderTelemetryMiddleware struct {
	next interfaces.OrderInterface
}

func NewOrderTelemetryMiddleware(next interfaces.OrderInterface) interfaces.OrderInterface {
	return &OrderTelemetryMiddleware{next: next}
}

func (m *OrderTelemetryMiddleware) AddItems(ctx context.Context, orderID uuid.UUID, orgID uuid.UUID, req *models.AddOrderItemsRequest) (*models.Order, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.AddItems")
	return m.next.AddItems(ctx, orderID, orgID, req)
}

func (m *OrderTelemetryMiddleware) CloseAllOrders(ctx context.Context, orgID uuid.UUID) (int64, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.CloseAllOrders")
	return m.next.CloseAllOrders(ctx, orgID)
}

func (m *OrderTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Order, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.GetByID")
	return m.next.GetByID(ctx, id, orgID)
}

func (m *OrderTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, orderType string, status string, bookingID *uuid.UUID, from *time.Time, to *time.Time, page int, pageSize int) ([]models.Order, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.List")
	return m.next.List(ctx, orgID, branchID, orderType, status, bookingID, from, to, page, pageSize)
}

func (m *OrderTelemetryMiddleware) ListCheckedInGuests(ctx context.Context, orgID uuid.UUID) ([]repository.InHouseGuest, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.ListCheckedInGuests")
	return m.next.ListCheckedInGuests(ctx, orgID)
}

func (m *OrderTelemetryMiddleware) PlaceOrder(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.PlaceOrderRequest) (*models.Order, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.PlaceOrder")
	return m.next.PlaceOrder(ctx, orgID, branchID, req)
}

func (m *OrderTelemetryMiddleware) PlaceWalkInOrder(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.PlaceWalkInOrderRequest) (*models.Order, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.PlaceWalkInOrder")
	return m.next.PlaceWalkInOrder(ctx, orgID, branchID, req)
}

func (m *OrderTelemetryMiddleware) RemoveItem(ctx context.Context, itemID uuid.UUID, orderID uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Order.RemoveItem")
	return m.next.RemoveItem(ctx, itemID, orderID, orgID)
}

func (m *OrderTelemetryMiddleware) UpdateBarStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (*models.Order, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.UpdateBarStatus")
	return m.next.UpdateBarStatus(ctx, id, orgID, status)
}

func (m *OrderTelemetryMiddleware) UpdateKitchenStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (*models.Order, error) {
	trace.SpanFromContext(ctx).AddEvent("Order.UpdateKitchenStatus")
	return m.next.UpdateKitchenStatus(ctx, id, orgID, status)
}
