// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type OrganizationSettingsTelemetryMiddleware struct {
	next interfaces.OrganizationSettingsInterface
}

func NewOrganizationSettingsTelemetryMiddleware(next interfaces.OrganizationSettingsInterface) interfaces.OrganizationSettingsInterface {
	return &OrganizationSettingsTelemetryMiddleware{next: next}
}

func (m *OrganizationSettingsTelemetryMiddleware) Get(ctx context.Context, orgID uuid.UUID) (*models.OrganizationSettings, error) {
	trace.SpanFromContext(ctx).AddEvent("OrganizationSettings.Get")
	return m.next.Get(ctx, orgID)
}

func (m *OrganizationSettingsTelemetryMiddleware) Upsert(ctx context.Context, orgID uuid.UUID, req *models.UpdateOrganizationSettingsRequest) (*models.OrganizationSettings, error) {
	trace.SpanFromContext(ctx).AddEvent("OrganizationSettings.Upsert")
	return m.next.Upsert(ctx, orgID, req)
}
