// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type PasswordPolicyTelemetryMiddleware struct {
	next interfaces.PasswordPolicyInterface
}

func NewPasswordPolicyTelemetryMiddleware(next interfaces.PasswordPolicyInterface) interfaces.PasswordPolicyInterface {
	return &PasswordPolicyTelemetryMiddleware{next: next}
}

func (m *PasswordPolicyTelemetryMiddleware) CalculateLockoutTime(ctx context.Context, orgID ...uuid.UUID) time.Time {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.CalculateLockoutTime")
	return m.next.CalculateLockoutTime(ctx, orgID...)
}

func (m *PasswordPolicyTelemetryMiddleware) CalculatePasswordExpiry(ctx context.Context, orgID ...uuid.UUID) *time.Time {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.CalculatePasswordExpiry")
	return m.next.CalculatePasswordExpiry(ctx, orgID...)
}

func (m *PasswordPolicyTelemetryMiddleware) CheckAccountLockout(ctx context.Context, user *models.User) (bool, string) {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.CheckAccountLockout")
	return m.next.CheckAccountLockout(ctx, user)
}

func (m *PasswordPolicyTelemetryMiddleware) CheckPasswordExpiry(ctx context.Context, user *models.User) (bool, bool, int) {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.CheckPasswordExpiry")
	return m.next.CheckPasswordExpiry(ctx, user)
}

func (m *PasswordPolicyTelemetryMiddleware) GetPolicy(ctx context.Context, orgID ...uuid.UUID) *models.PasswordPolicy {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.GetPolicy")
	return m.next.GetPolicy(ctx, orgID...)
}

func (m *PasswordPolicyTelemetryMiddleware) GetSessionTimeout(ctx context.Context, orgID ...uuid.UUID) int {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.GetSessionTimeout")
	return m.next.GetSessionTimeout(ctx, orgID...)
}

func (m *PasswordPolicyTelemetryMiddleware) LoadGlobalPolicy(ctx context.Context) error {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.LoadGlobalPolicy")
	return m.next.LoadGlobalPolicy(ctx)
}

func (m *PasswordPolicyTelemetryMiddleware) RecordPasswordChange(ctx context.Context, userID uuid.UUID, passwordHash string) error {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.RecordPasswordChange")
	return m.next.RecordPasswordChange(ctx, userID, passwordHash)
}

func (m *PasswordPolicyTelemetryMiddleware) ShouldLockAccount(ctx context.Context, failedAttempts int, orgID ...uuid.UUID) bool {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.ShouldLockAccount")
	return m.next.ShouldLockAccount(ctx, failedAttempts, orgID...)
}

func (m *PasswordPolicyTelemetryMiddleware) UpsertPolicy(ctx context.Context, orgID uuid.UUID, req *models.CreatePasswordPolicyRequest) (*models.PasswordPolicy, error) {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.UpsertPolicy")
	return m.next.UpsertPolicy(ctx, orgID, req)
}

func (m *PasswordPolicyTelemetryMiddleware) ValidateNewPassword(ctx context.Context, userID uuid.UUID, newPassword string, currentPasswordHash string, orgID ...uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("PasswordPolicy.ValidateNewPassword")
	return m.next.ValidateNewPassword(ctx, userID, newPassword, currentPasswordHash, orgID...)
}
