// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type ReviewTelemetryMiddleware struct {
	next interfaces.ReviewInterface
}

func NewReviewTelemetryMiddleware(next interfaces.ReviewInterface) interfaces.ReviewInterface {
	return &ReviewTelemetryMiddleware{next: next}
}

func (m *ReviewTelemetryMiddleware) GetSummary(ctx context.Context) (*models.RatingSummary, error) {
	trace.SpanFromContext(ctx).AddEvent("Review.GetSummary")
	return m.next.GetSummary(ctx)
}

func (m *ReviewTelemetryMiddleware) Submit(ctx context.Context, userID uuid.UUID, req *models.SubmitReviewRequest) (*models.Review, error) {
	trace.SpanFromContext(ctx).AddEvent("Review.Submit")
	return m.next.Submit(ctx, userID, req)
}
