// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type RoleTelemetryMiddleware struct {
	next interfaces.RoleInterface
}

func NewRoleTelemetryMiddleware(next interfaces.RoleInterface) interfaces.RoleInterface {
	return &RoleTelemetryMiddleware{next: next}
}

func (m *RoleTelemetryMiddleware) GetAllRoles(ctx context.Context, orgID uuid.UUID) ([]models.Role, error) {
	trace.SpanFromContext(ctx).AddEvent("Role.GetAllRoles")
	return m.next.GetAllRoles(ctx, orgID)
}

func (m *RoleTelemetryMiddleware) InitializePredefinedRoles(ctx context.Context) error {
	trace.SpanFromContext(ctx).AddEvent("Role.InitializePredefinedRoles")
	return m.next.InitializePredefinedRoles(ctx)
}
