// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type RoomTelemetryMiddleware struct {
	next interfaces.RoomInterface
}

func NewRoomTelemetryMiddleware(next interfaces.RoomInterface) interfaces.RoomInterface {
	return &RoomTelemetryMiddleware{next: next}
}

func (m *RoomTelemetryMiddleware) Create(ctx context.Context, room *models.Room, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Room.Create")
	return m.next.Create(ctx, room, orgID)
}

func (m *RoomTelemetryMiddleware) Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Room.Delete")
	return m.next.Delete(ctx, id, orgID)
}

func (m *RoomTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Room, error) {
	trace.SpanFromContext(ctx).AddEvent("Room.GetByID")
	return m.next.GetByID(ctx, id, orgID)
}

func (m *RoomTelemetryMiddleware) GetByIDUnscoped(ctx context.Context, id uuid.UUID) (*models.Room, error) {
	trace.SpanFromContext(ctx).AddEvent("Room.GetByIDUnscoped")
	return m.next.GetByIDUnscoped(ctx, id)
}

func (m *RoomTelemetryMiddleware) GuestList(ctx context.Context, orgID *uuid.UUID, branchID *uuid.UUID, roomType string, orgName string, isAvailable *bool, page int, pageSize int) ([]models.Room, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Room.GuestList")
	return m.next.GuestList(ctx, orgID, branchID, roomType, orgName, isAvailable, page, pageSize)
}

func (m *RoomTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, roomType string, isAvailable *bool, page int, pageSize int) ([]models.Room, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Room.List")
	return m.next.List(ctx, orgID, branchID, roomType, isAvailable, page, pageSize)
}

func (m *RoomTelemetryMiddleware) ListAvailable(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, checkIn time.Time, checkOut time.Time, roomType string) ([]models.Room, error) {
	trace.SpanFromContext(ctx).AddEvent("Room.ListAvailable")
	return m.next.ListAvailable(ctx, orgID, branchID, checkIn, checkOut, roomType)
}

func (m *RoomTelemetryMiddleware) ListRoomStatus(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) ([]models.RoomStatus, error) {
	trace.SpanFromContext(ctx).AddEvent("Room.ListRoomStatus")
	return m.next.ListRoomStatus(ctx, orgID, branchID)
}

func (m *RoomTelemetryMiddleware) SetAvailability(ctx context.Context, id uuid.UUID, orgID uuid.UUID, available bool) error {
	trace.SpanFromContext(ctx).AddEvent("Room.SetAvailability")
	return m.next.SetAvailability(ctx, id, orgID, available)
}

func (m *RoomTelemetryMiddleware) Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.Room) (*models.Room, error) {
	trace.SpanFromContext(ctx).AddEvent("Room.Update")
	return m.next.Update(ctx, id, orgID, updates)
}

func (m *RoomTelemetryMiddleware) UpdateImages(ctx context.Context, id uuid.UUID, orgID uuid.UUID, images []string) (*models.Room, error) {
	trace.SpanFromContext(ctx).AddEvent("Room.UpdateImages")
	return m.next.UpdateImages(ctx, id, orgID, images)
}
