// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type UserTelemetryMiddleware struct {
	next interfaces.UserInterface
}

func NewUserTelemetryMiddleware(next interfaces.UserInterface) interfaces.UserInterface {
	return &UserTelemetryMiddleware{next: next}
}

func (m *UserTelemetryMiddleware) ChangePassword(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) error {
	trace.SpanFromContext(ctx).AddEvent("User.ChangePassword")
	return m.next.ChangePassword(ctx, userID, oldPassword, newPassword)
}

func (m *UserTelemetryMiddleware) ChangeUserRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (*models.User, error) {
	trace.SpanFromContext(ctx).AddEvent("User.ChangeUserRole")
	return m.next.ChangeUserRole(ctx, userID, roleID)
}

func (m *UserTelemetryMiddleware) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("User.DeactivateUser")
	return m.next.DeactivateUser(ctx, id)
}

func (m *UserTelemetryMiddleware) DeleteUser(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("User.DeleteUser")
	return m.next.DeleteUser(ctx, id, orgID)
}

func (m *UserTelemetryMiddleware) GetAllUsers(ctx context.Context) ([]models.User, error) {
	trace.SpanFromContext(ctx).AddEvent("User.GetAllUsers")
	return m.next.GetAllUsers(ctx)
}

func (m *UserTelemetryMiddleware) GetByEmail(ctx context.Context, emailAddr string) (*models.User, error) {
	trace.SpanFromContext(ctx).AddEvent("User.GetByEmail")
	return m.next.GetByEmail(ctx, emailAddr)
}

func (m *UserTelemetryMiddleware) GetUserByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	trace.SpanFromContext(ctx).AddEvent("User.GetUserByID")
	return m.next.GetUserByID(ctx, id)
}

func (m *UserTelemetryMiddleware) ListUsers(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, search string, roleID *uuid.UUID, isActive *bool, page int, pageSize int) ([]models.User, int, error) {
	trace.SpanFromContext(ctx).AddEvent("User.ListUsers")
	return m.next.ListUsers(ctx, orgID, branchID, search, roleID, isActive, page, pageSize)
}

func (m *UserTelemetryMiddleware) LockUser(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("User.LockUser")
	return m.next.LockUser(ctx, id)
}

func (m *UserTelemetryMiddleware) Login(ctx context.Context, emailAddr string, pwd string) (map[string]interface{}, error) {
	trace.SpanFromContext(ctx).AddEvent("User.Login")
	return m.next.Login(ctx, emailAddr, pwd)
}

func (m *UserTelemetryMiddleware) LoginWithOrg(ctx context.Context, emailAddr string, pwd string, orgID uuid.UUID) (map[string]interface{}, error) {
	trace.SpanFromContext(ctx).AddEvent("User.LoginWithOrg")
	return m.next.LoginWithOrg(ctx, emailAddr, pwd, orgID)
}

func (m *UserTelemetryMiddleware) Register(ctx context.Context, user *models.User) error {
	trace.SpanFromContext(ctx).AddEvent("User.Register")
	return m.next.Register(ctx, user)
}

func (m *UserTelemetryMiddleware) ResetPassword(ctx context.Context, userID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("User.ResetPassword")
	return m.next.ResetPassword(ctx, userID)
}

func (m *UserTelemetryMiddleware) UnlockUser(ctx context.Context, id uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("User.UnlockUser")
	return m.next.UnlockUser(ctx, id)
}

func (m *UserTelemetryMiddleware) UpdateUser(ctx context.Context, updates *models.User) (*models.User, error) {
	trace.SpanFromContext(ctx).AddEvent("User.UpdateUser")
	return m.next.UpdateUser(ctx, updates)
}

func (m *UserTelemetryMiddleware) UpdateUserFull(ctx context.Context, id uuid.UUID, callerID uuid.UUID, fullName string, newEmail string, pwd string, roleName string, status string, branchID *uuid.UUID) (*models.User, error) {
	trace.SpanFromContext(ctx).AddEvent("User.UpdateUserFull")
	return m.next.UpdateUserFull(ctx, id, callerID, fullName, newEmail, pwd, roleName, status, branchID)
}
