// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type VenueTelemetryMiddleware struct {
	next interfaces.VenueInterface
}

func NewVenueTelemetryMiddleware(next interfaces.VenueInterface) interfaces.VenueInterface {
	return &VenueTelemetryMiddleware{next: next}
}

func (m *VenueTelemetryMiddleware) Create(ctx context.Context, venue *models.Venue, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Venue.Create")
	return m.next.Create(ctx, venue, orgID)
}

func (m *VenueTelemetryMiddleware) Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	trace.SpanFromContext(ctx).AddEvent("Venue.Delete")
	return m.next.Delete(ctx, id, orgID)
}

func (m *VenueTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (*models.Venue, error) {
	trace.SpanFromContext(ctx).AddEvent("Venue.GetByID")
	return m.next.GetByID(ctx, id, orgID)
}

func (m *VenueTelemetryMiddleware) GetByIDUnscoped(ctx context.Context, id uuid.UUID) (*models.Venue, error) {
	trace.SpanFromContext(ctx).AddEvent("Venue.GetByIDUnscoped")
	return m.next.GetByIDUnscoped(ctx, id)
}

func (m *VenueTelemetryMiddleware) GuestList(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, venueType string, from *time.Time, to *time.Time) ([]models.Venue, error) {
	trace.SpanFromContext(ctx).AddEvent("Venue.GuestList")
	return m.next.GuestList(ctx, orgID, branchID, venueType, from, to)
}

func (m *VenueTelemetryMiddleware) List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, venueType string, isAvailable *bool, from *time.Time, to *time.Time, page int, pageSize int) ([]models.Venue, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Venue.List")
	return m.next.List(ctx, orgID, branchID, venueType, isAvailable, from, to, page, pageSize)
}

func (m *VenueTelemetryMiddleware) SetAvailability(ctx context.Context, id uuid.UUID, orgID uuid.UUID, available bool) error {
	trace.SpanFromContext(ctx).AddEvent("Venue.SetAvailability")
	return m.next.SetAvailability(ctx, id, orgID, available)
}

func (m *VenueTelemetryMiddleware) Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.Venue) (*models.Venue, error) {
	trace.SpanFromContext(ctx).AddEvent("Venue.Update")
	return m.next.Update(ctx, id, orgID, updates)
}

func (m *VenueTelemetryMiddleware) UpdateImages(ctx context.Context, id uuid.UUID, orgID uuid.UUID, images []string) (*models.Venue, error) {
	trace.SpanFromContext(ctx).AddEvent("Venue.UpdateImages")
	return m.next.UpdateImages(ctx, id, orgID, images)
}
