// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type WebUserAuthTelemetryMiddleware struct {
	next interfaces.WebUserAuthInterface
}

func NewWebUserAuthTelemetryMiddleware(next interfaces.WebUserAuthInterface) interfaces.WebUserAuthInterface {
	return &WebUserAuthTelemetryMiddleware{next: next}
}

func (m *WebUserAuthTelemetryMiddleware) ChangePassword(ctx context.Context, id uuid.UUID, oldPassword string, newPassword string) error {
	trace.SpanFromContext(ctx).AddEvent("WebUserAuth.ChangePassword")
	return m.next.ChangePassword(ctx, id, oldPassword, newPassword)
}

func (m *WebUserAuthTelemetryMiddleware) GetByID(ctx context.Context, id uuid.UUID) (*models.WebUser, error) {
	trace.SpanFromContext(ctx).AddEvent("WebUserAuth.GetByID")
	return m.next.GetByID(ctx, id)
}

func (m *WebUserAuthTelemetryMiddleware) Login(ctx context.Context, req *models.WebUserLoginRequest) (*models.WebUser, string, error) {
	trace.SpanFromContext(ctx).AddEvent("WebUserAuth.Login")
	return m.next.Login(ctx, req)
}

func (m *WebUserAuthTelemetryMiddleware) Register(ctx context.Context, req *models.WebUserRegisterRequest) (*models.WebUser, error) {
	trace.SpanFromContext(ctx).AddEvent("WebUserAuth.Register")
	return m.next.Register(ctx, req)
}

func (m *WebUserAuthTelemetryMiddleware) Update(ctx context.Context, id uuid.UUID, req *models.WebUserUpdateRequest) (*models.WebUser, error) {
	trace.SpanFromContext(ctx).AddEvent("WebUserAuth.Update")
	return m.next.Update(ctx, id, req)
}
