// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package telemetry

import (
	"context"

	"go.opentelemetry.io/otel/trace"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type WorkflowTelemetryMiddleware struct {
	next interfaces.WorkflowInterface
}

func NewWorkflowTelemetryMiddleware(next interfaces.WorkflowInterface) interfaces.WorkflowInterface {
	return &WorkflowTelemetryMiddleware{next: next}
}

func (m *WorkflowTelemetryMiddleware) CancelInstance(ctx context.Context, taskID string, orgID string) error {
	trace.SpanFromContext(ctx).AddEvent("Workflow.CancelInstance")
	return m.next.CancelInstance(ctx, taskID, orgID)
}

func (m *WorkflowTelemetryMiddleware) GetAllOrgTasks(ctx context.Context, orgID string, branchID string, statusFilter string, page int, pageSize int) ([]models.AssignedTask, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Workflow.GetAllOrgTasks")
	return m.next.GetAllOrgTasks(ctx, orgID, branchID, statusFilter, page, pageSize)
}

func (m *WorkflowTelemetryMiddleware) GetInstanceByTaskID(ctx context.Context, taskID string, orgID string) (*models.WorkflowInstance, error) {
	trace.SpanFromContext(ctx).AddEvent("Workflow.GetInstanceByTaskID")
	return m.next.GetInstanceByTaskID(ctx, taskID, orgID)
}

func (m *WorkflowTelemetryMiddleware) GetInstanceHistory(ctx context.Context, instanceID string, orgID string) ([]models.WorkflowHistory, error) {
	trace.SpanFromContext(ctx).AddEvent("Workflow.GetInstanceHistory")
	return m.next.GetInstanceHistory(ctx, instanceID, orgID)
}

func (m *WorkflowTelemetryMiddleware) GetMyTasks(ctx context.Context, orgID string, userID string, statusFilter string, page int, pageSize int) ([]models.AssignedTask, int, error) {
	trace.SpanFromContext(ctx).AddEvent("Workflow.GetMyTasks")
	return m.next.GetMyTasks(ctx, orgID, userID, statusFilter, page, pageSize)
}

func (m *WorkflowTelemetryMiddleware) GetTaskByID(ctx context.Context, taskID string, orgID string) (*models.AssignedTask, error) {
	trace.SpanFromContext(ctx).AddEvent("Workflow.GetTaskByID")
	return m.next.GetTaskByID(ctx, taskID, orgID)
}

func (m *WorkflowTelemetryMiddleware) InitiateWorkflow(ctx context.Context, workflowType models.WorkflowType, taskDetails models.TaskDetails, initiatorID string, priority string, dueDate interface{}, orgID string) (*models.WorkflowInstance, error) {
	trace.SpanFromContext(ctx).AddEvent("Workflow.InitiateWorkflow")
	return m.next.InitiateWorkflow(ctx, workflowType, taskDetails, initiatorID, priority, dueDate, orgID)
}

func (m *WorkflowTelemetryMiddleware) ProcessAction(ctx context.Context, instanceID string, action string, performedByID string, comments string, orgID string) error {
	trace.SpanFromContext(ctx).AddEvent("Workflow.ProcessAction")
	return m.next.ProcessAction(ctx, instanceID, action, performedByID, comments, orgID)
}
