// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type AuditLogLoggerMiddleware struct {
	next interfaces.AuditLogInterface
}

func NewAuditLogLoggerMiddleware(next interfaces.AuditLogInterface) interfaces.AuditLogInterface {
	return &AuditLogLoggerMiddleware{next: next}
}

func (m *AuditLogLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID, entityType string, entityID string, action string, from *time.Time, to *time.Time, page int, pageSize int) (_ []models.AuditLog, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("AuditLog.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("AuditLog.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID, entityType, entityID, action, from, to, page, pageSize)
}
