// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type BackofficeAuthLoggerMiddleware struct {
	next interfaces.BackofficeAuthInterface
}

func NewBackofficeAuthLoggerMiddleware(next interfaces.BackofficeAuthInterface) interfaces.BackofficeAuthInterface {
	return &BackofficeAuthLoggerMiddleware{next: next}
}

func (m *BackofficeAuthLoggerMiddleware) ChangePassword(ctx context.Context, id uuid.UUID, currentPassword string, newPassword string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeAuth.ChangePassword", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeAuth.ChangePassword", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ChangePassword(ctx, id, currentPassword, newPassword)
}

func (m *BackofficeAuthLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID) (_ *models.BackofficeUser, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeAuth.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeAuth.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id)
}

func (m *BackofficeAuthLoggerMiddleware) Login(ctx context.Context, emailAddr string, password string) (_ *models.BackofficeUser, _ string, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeAuth.Login", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeAuth.Login", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Login(ctx, emailAddr, password)
}

func (m *BackofficeAuthLoggerMiddleware) ResetPassword(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeAuth.ResetPassword", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeAuth.ResetPassword", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ResetPassword(ctx, id)
}
