// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type BackofficeOrganizationLoggerMiddleware struct {
	next interfaces.BackofficeOrganizationInterface
}

func NewBackofficeOrganizationLoggerMiddleware(next interfaces.BackofficeOrganizationInterface) interfaces.BackofficeOrganizationInterface {
	return &BackofficeOrganizationLoggerMiddleware{next: next}
}

func (m *BackofficeOrganizationLoggerMiddleware) Delete(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeOrganization.Delete", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeOrganization.Delete", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Delete(ctx, id)
}

func (m *BackofficeOrganizationLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID) (_ *models.Organization, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeOrganization.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeOrganization.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id)
}

func (m *BackofficeOrganizationLoggerMiddleware) List(ctx context.Context) (_ []models.Organization, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeOrganization.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeOrganization.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx)
}

func (m *BackofficeOrganizationLoggerMiddleware) Provision(ctx context.Context, req models.ProvisionOrgRequest) (_ *models.Organization, _ *models.User, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeOrganization.Provision", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeOrganization.Provision", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Provision(ctx, req)
}

func (m *BackofficeOrganizationLoggerMiddleware) ToggleStatus(ctx context.Context, id uuid.UUID, isActive bool) (_ *models.Organization, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeOrganization.ToggleStatus", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeOrganization.ToggleStatus", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ToggleStatus(ctx, id, isActive)
}

func (m *BackofficeOrganizationLoggerMiddleware) Update(ctx context.Context, id uuid.UUID, req models.OrgDetails) (_ *models.Organization, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeOrganization.Update", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeOrganization.Update", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Update(ctx, id, req)
}
