// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type BackofficeUserLoggerMiddleware struct {
	next interfaces.BackofficeUserInterface
}

func NewBackofficeUserLoggerMiddleware(next interfaces.BackofficeUserInterface) interfaces.BackofficeUserInterface {
	return &BackofficeUserLoggerMiddleware{next: next}
}

func (m *BackofficeUserLoggerMiddleware) Create(ctx context.Context, req models.CreateBackofficeUserRequest) (_ *models.BackofficeUser, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeUser.Create", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeUser.Create", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Create(ctx, req)
}

func (m *BackofficeUserLoggerMiddleware) Delete(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeUser.Delete", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeUser.Delete", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Delete(ctx, id)
}

func (m *BackofficeUserLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID) (_ *models.BackofficeUser, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeUser.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeUser.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id)
}

func (m *BackofficeUserLoggerMiddleware) List(ctx context.Context) (_ []models.BackofficeUser, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeUser.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeUser.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx)
}

func (m *BackofficeUserLoggerMiddleware) Lock(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeUser.Lock", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeUser.Lock", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Lock(ctx, id)
}

func (m *BackofficeUserLoggerMiddleware) ResetPassword(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeUser.ResetPassword", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeUser.ResetPassword", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ResetPassword(ctx, id)
}

func (m *BackofficeUserLoggerMiddleware) Unlock(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeUser.Unlock", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeUser.Unlock", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Unlock(ctx, id)
}

func (m *BackofficeUserLoggerMiddleware) Update(ctx context.Context, id uuid.UUID, req models.UpdateBackofficeUserRequest) (_ *models.BackofficeUser, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("BackofficeUser.Update", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("BackofficeUser.Update", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Update(ctx, id, req)
}
