// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"encoding/json"
	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
	"lodge-system/internal/repository"
)

type BookingLoggerMiddleware struct {
	next interfaces.BookingInterface
}

func NewBookingLoggerMiddleware(next interfaces.BookingInterface) interfaces.BookingInterface {
	return &BookingLoggerMiddleware{next: next}
}

func (m *BookingLoggerMiddleware) AddAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.CreateAttendeeRequest) (_ *models.BookingAttendee, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.AddAttendee", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.AddAttendee", zap.Duration("took", time.Since(start)))
	}()
	return m.next.AddAttendee(ctx, id, orgID, req)
}

func (m *BookingLoggerMiddleware) AssignRoom(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.CreateRoomAssignmentRequest) (_ *models.BookingRoomAssignment, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.AssignRoom", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.AssignRoom", zap.Duration("took", time.Since(start)))
	}()
	return m.next.AssignRoom(ctx, id, orgID, req)
}

func (m *BookingLoggerMiddleware) Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.Cancel", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.Cancel", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Cancel(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) CancelForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) (_ uuid.UUID, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CancelForWebUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CancelForWebUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CancelForWebUser(ctx, id, webUserID)
}

func (m *BookingLoggerMiddleware) CheckIn(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CheckIn", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CheckIn", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CheckIn(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) CheckInAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CheckInAssignment", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CheckInAssignment", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CheckInAssignment(ctx, id, orgID, assignmentID)
}

func (m *BookingLoggerMiddleware) CheckOut(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CheckOut", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CheckOut", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CheckOut(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) CheckOutAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CheckOutAssignment", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CheckOutAssignment", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CheckOutAssignment(ctx, id, orgID, assignmentID)
}

func (m *BookingLoggerMiddleware) CreateCorporateAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, envelope *models.SubmitAccommodationRequest, matReq *models.MaterialiseRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CreateCorporateAccommodation", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CreateCorporateAccommodation", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateCorporateAccommodation(ctx, orgID, branchID, corProfileID, companyID, envelope, matReq)
}

func (m *BookingLoggerMiddleware) CreateCorporateEvent(ctx context.Context, orgID uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitEventBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CreateCorporateEvent", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CreateCorporateEvent", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateCorporateEvent(ctx, orgID, corProfileID, companyID, webUserID, promoteID, envelope)
}

func (m *BookingLoggerMiddleware) CreateCorporateMeal(ctx context.Context, orgID uuid.UUID, corProfileID *uuid.UUID, companyID *uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitMealBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CreateCorporateMeal", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CreateCorporateMeal", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateCorporateMeal(ctx, orgID, corProfileID, companyID, webUserID, promoteID, envelope)
}

func (m *BookingLoggerMiddleware) CreateFromBooking(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, bookingID uuid.UUID, matReq *models.MaterialiseRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CreateFromBooking", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CreateFromBooking", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateFromBooking(ctx, orgID, branchID, bookingID, matReq)
}

func (m *BookingLoggerMiddleware) CreateIndividual(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.CreateIndividualBookingRequest, metadata json.RawMessage) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CreateIndividual", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CreateIndividual", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateIndividual(ctx, orgID, branchID, req, metadata)
}

func (m *BookingLoggerMiddleware) CreateIndividualEvent(ctx context.Context, orgID uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitEventBookingRequest, metadata json.RawMessage) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CreateIndividualEvent", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CreateIndividualEvent", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateIndividualEvent(ctx, orgID, webUserID, promoteID, envelope, metadata)
}

func (m *BookingLoggerMiddleware) CreateIndividualMeal(ctx context.Context, orgID uuid.UUID, webUserID *uuid.UUID, promoteID *uuid.UUID, envelope *models.SubmitMealBookingRequest, metadata json.RawMessage) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CreateIndividualMeal", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CreateIndividualMeal", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateIndividualMeal(ctx, orgID, webUserID, promoteID, envelope, metadata)
}

func (m *BookingLoggerMiddleware) CreateIndividualRooms(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, promoteID uuid.UUID, webUserID *uuid.UUID, bookerName string, bookerEmail string, bookerPhone string, envelope *models.SubmitIndividualBookingRequest, metadata json.RawMessage) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.CreateIndividualRooms", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.CreateIndividualRooms", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateIndividualRooms(ctx, orgID, branchID, promoteID, webUserID, bookerName, bookerEmail, bookerPhone, envelope, metadata)
}

func (m *BookingLoggerMiddleware) FindOverdueCheckouts(ctx context.Context, orgIDs []uuid.UUID) (_ []repository.OverdueBookingRef, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.FindOverdueCheckouts", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.FindOverdueCheckouts", zap.Duration("took", time.Since(start)))
	}()
	return m.next.FindOverdueCheckouts(ctx, orgIDs)
}

func (m *BookingLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) GetByIDUnscoped(ctx context.Context, id uuid.UUID) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.GetByIDUnscoped", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.GetByIDUnscoped", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByIDUnscoped(ctx, id)
}

func (m *BookingLoggerMiddleware) GetForApproval(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.GetForApproval", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.GetForApproval", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetForApproval(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID, bookerType string, bookingType string, status string, from *time.Time, to *time.Time, page int, pageSize int) (_ []models.Booking, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID, bookerType, bookingType, status, from, to, page, pageSize)
}

func (m *BookingLoggerMiddleware) ListAssignments(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ []models.BookingRoomAssignment, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.ListAssignments", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.ListAssignments", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListAssignments(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) ListAttendees(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ []models.BookingAttendee, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.ListAttendees", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.ListAttendees", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListAttendees(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) ListForExport(ctx context.Context, orgID uuid.UUID, bookerType string, bookingType string, status string, from *time.Time, to *time.Time) (_ []models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.ListForExport", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.ListForExport", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListForExport(ctx, orgID, bookerType, bookingType, status, from, to)
}

func (m *BookingLoggerMiddleware) ListForWebUser(ctx context.Context, webUserID uuid.UUID, page int, pageSize int) (_ []models.Booking, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.ListForWebUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.ListForWebUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListForWebUser(ctx, webUserID, page, pageSize)
}

func (m *BookingLoggerMiddleware) MarkOverstayed(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.MarkOverstayed", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.MarkOverstayed", zap.Duration("took", time.Since(start)))
	}()
	return m.next.MarkOverstayed(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) RecalculateTotal(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.RecalculateTotal", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.RecalculateTotal", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RecalculateTotal(ctx, id, orgID)
}

func (m *BookingLoggerMiddleware) RemoveAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.RemoveAssignment", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.RemoveAssignment", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RemoveAssignment(ctx, id, orgID, assignmentID)
}

func (m *BookingLoggerMiddleware) RemoveAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, attendeeID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.RemoveAttendee", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.RemoveAttendee", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RemoveAttendee(ctx, id, orgID, attendeeID)
}

func (m *BookingLoggerMiddleware) SetStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, newStatus string, fromStatus string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.SetStatus", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.SetStatus", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SetStatus(ctx, id, orgID, newStatus, fromStatus)
}

func (m *BookingLoggerMiddleware) SubmitPending(ctx context.Context, in *models.PendingBookingInput) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.SubmitPending", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.SubmitPending", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SubmitPending(ctx, in)
}

func (m *BookingLoggerMiddleware) UpdateAssignment(ctx context.Context, id uuid.UUID, orgID uuid.UUID, assignmentID uuid.UUID, req *models.UpdateRoomAssignmentRequest) (_ *models.BookingRoomAssignment, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.UpdateAssignment", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.UpdateAssignment", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateAssignment(ctx, id, orgID, assignmentID, req)
}

func (m *BookingLoggerMiddleware) UpdateAttendee(ctx context.Context, id uuid.UUID, orgID uuid.UUID, attendeeID uuid.UUID, req *models.UpdateAttendeeRequest) (_ *models.BookingAttendee, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.UpdateAttendee", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.UpdateAttendee", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateAttendee(ctx, id, orgID, attendeeID, req)
}

func (m *BookingLoggerMiddleware) UpdateStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, newStatus string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Booking.UpdateStatus", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Booking.UpdateStatus", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateStatus(ctx, id, orgID, newStatus)
}
