// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type BranchLoggerMiddleware struct {
	next interfaces.BranchInterface
}

func NewBranchLoggerMiddleware(next interfaces.BranchInterface) interfaces.BranchInterface {
	return &BranchLoggerMiddleware{next: next}
}

func (m *BranchLoggerMiddleware) Create(ctx context.Context, orgID uuid.UUID, req *models.CreateBranchRequest) (_ *models.Branch, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Branch.Create", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Branch.Create", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Create(ctx, orgID, req)
}

func (m *BranchLoggerMiddleware) Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Branch.Delete", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Branch.Delete", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Delete(ctx, id, orgID)
}

func (m *BranchLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.Branch, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Branch.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Branch.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id, orgID)
}

func (m *BranchLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID) (_ []models.Branch, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Branch.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Branch.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID)
}

func (m *BranchLoggerMiddleware) Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateBranchRequest) (_ *models.Branch, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Branch.Update", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Branch.Update", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Update(ctx, id, orgID, req)
}
