// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type ClientLoggerMiddleware struct {
	next interfaces.ClientInterface
}

func NewClientLoggerMiddleware(next interfaces.ClientInterface) interfaces.ClientInterface {
	return &ClientLoggerMiddleware{next: next}
}

func (m *ClientLoggerMiddleware) CreateCorporate(ctx context.Context, orgID uuid.UUID, c *models.CorporateClient) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.CreateCorporate", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.CreateCorporate", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateCorporate(ctx, orgID, c)
}

func (m *ClientLoggerMiddleware) CreateIndividual(ctx context.Context, orgID uuid.UUID, c *models.IndividualClient) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.CreateIndividual", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.CreateIndividual", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateIndividual(ctx, orgID, c)
}

func (m *ClientLoggerMiddleware) DeleteCorporate(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.DeleteCorporate", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.DeleteCorporate", zap.Duration("took", time.Since(start)))
	}()
	return m.next.DeleteCorporate(ctx, id, orgID)
}

func (m *ClientLoggerMiddleware) DeleteIndividual(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.DeleteIndividual", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.DeleteIndividual", zap.Duration("took", time.Since(start)))
	}()
	return m.next.DeleteIndividual(ctx, id, orgID)
}

func (m *ClientLoggerMiddleware) GetCorporateByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.CorporateClient, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.GetCorporateByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.GetCorporateByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetCorporateByID(ctx, id, orgID)
}

func (m *ClientLoggerMiddleware) GetCorporateWithBookings(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.CorporateClientWithBookings, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.GetCorporateWithBookings", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.GetCorporateWithBookings", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetCorporateWithBookings(ctx, id, orgID)
}

func (m *ClientLoggerMiddleware) GetIndividualByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.IndividualClient, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.GetIndividualByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.GetIndividualByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetIndividualByID(ctx, id, orgID)
}

func (m *ClientLoggerMiddleware) ListCorporate(ctx context.Context, orgID uuid.UUID, search string, status string, page int, pageSize int) (_ []models.CorporateClient, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.ListCorporate", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.ListCorporate", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListCorporate(ctx, orgID, search, status, page, pageSize)
}

func (m *ClientLoggerMiddleware) ListIndividual(ctx context.Context, orgID uuid.UUID, search string, status string, page int, pageSize int) (_ []models.IndividualClient, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.ListIndividual", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.ListIndividual", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListIndividual(ctx, orgID, search, status, page, pageSize)
}

func (m *ClientLoggerMiddleware) LookupIndividualByIDNumber(ctx context.Context, orgID uuid.UUID, idNumber string) (_ *models.IndividualClient, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.LookupIndividualByIDNumber", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.LookupIndividualByIDNumber", zap.Duration("took", time.Since(start)))
	}()
	return m.next.LookupIndividualByIDNumber(ctx, orgID, idNumber)
}

func (m *ClientLoggerMiddleware) SearchCorporate(ctx context.Context, orgID uuid.UUID, search string) (_ []models.CorporateClient, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.SearchCorporate", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.SearchCorporate", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SearchCorporate(ctx, orgID, search)
}

func (m *ClientLoggerMiddleware) UpdateCorporate(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.CorporateClient) (_ *models.CorporateClient, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.UpdateCorporate", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.UpdateCorporate", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateCorporate(ctx, id, orgID, updates)
}

func (m *ClientLoggerMiddleware) UpdateIndividual(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.IndividualClient) (_ *models.IndividualClient, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.UpdateIndividual", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.UpdateIndividual", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateIndividual(ctx, id, orgID, updates)
}

func (m *ClientLoggerMiddleware) UpsertDocuments(ctx context.Context, corporateClientID uuid.UUID, orgID uuid.UUID, urls []string) (_ *models.BookingDocument, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Client.UpsertDocuments", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Client.UpsertDocuments", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpsertDocuments(ctx, corporateClientID, orgID, urls)
}
