// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type CorProfileLoggerMiddleware struct {
	next interfaces.CorProfileInterface
}

func NewCorProfileLoggerMiddleware(next interfaces.CorProfileInterface) interfaces.CorProfileInterface {
	return &CorProfileLoggerMiddleware{next: next}
}

func (m *CorProfileLoggerMiddleware) AddGuest(ctx context.Context, profileID uuid.UUID, req *models.CreateCorporateGuestRequest) (_ *models.CorporateGuest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.AddGuest", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.AddGuest", zap.Duration("took", time.Since(start)))
	}()
	return m.next.AddGuest(ctx, profileID, req)
}

func (m *CorProfileLoggerMiddleware) CreateBranch(ctx context.Context, companyID uuid.UUID, req *models.CreateCorBranchRequest) (_ *models.CorBranchDetails, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.CreateBranch", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.CreateBranch", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateBranch(ctx, companyID, req)
}

func (m *CorProfileLoggerMiddleware) CreateProfile(ctx context.Context, orgID uuid.UUID, req *models.CreateCorProfileRequest) (_ *models.CorProfile, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.CreateProfile", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.CreateProfile", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateProfile(ctx, orgID, req)
}

func (m *CorProfileLoggerMiddleware) DeleteGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.DeleteGuest", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.DeleteGuest", zap.Duration("took", time.Since(start)))
	}()
	return m.next.DeleteGuest(ctx, id, profileID)
}

func (m *CorProfileLoggerMiddleware) GetBranch(ctx context.Context, id uuid.UUID, companyID uuid.UUID) (_ *models.CorBranchDetails, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.GetBranch", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.GetBranch", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetBranch(ctx, id, companyID)
}

func (m *CorProfileLoggerMiddleware) GetCompany(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.CorCompanyDetails, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.GetCompany", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.GetCompany", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetCompany(ctx, id, orgID)
}

func (m *CorProfileLoggerMiddleware) GetGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID) (_ *models.CorporateGuest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.GetGuest", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.GetGuest", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetGuest(ctx, id, profileID)
}

func (m *CorProfileLoggerMiddleware) GetProfile(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.CorProfile, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.GetProfile", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.GetProfile", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetProfile(ctx, id, orgID)
}

func (m *CorProfileLoggerMiddleware) ListBranches(ctx context.Context, companyID uuid.UUID) (_ []models.CorBranchDetails, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.ListBranches", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.ListBranches", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListBranches(ctx, companyID)
}

func (m *CorProfileLoggerMiddleware) ListCompanies(ctx context.Context, orgID uuid.UUID, page int, pageSize int) (_ []models.CorCompanyDetails, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.ListCompanies", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.ListCompanies", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListCompanies(ctx, orgID, page, pageSize)
}

func (m *CorProfileLoggerMiddleware) ListGuests(ctx context.Context, profileID uuid.UUID) (_ []models.CorporateGuest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.ListGuests", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.ListGuests", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListGuests(ctx, profileID)
}

func (m *CorProfileLoggerMiddleware) ListProfiles(ctx context.Context, companyID uuid.UUID, page int, pageSize int) (_ []models.CorProfile, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.ListProfiles", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.ListProfiles", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListProfiles(ctx, companyID, page, pageSize)
}

func (m *CorProfileLoggerMiddleware) ResolveChain(ctx context.Context, orgID uuid.UUID, company models.CorBookingCompanyInput, branch *models.CorBookingBranchInput, profile models.CorBookingProfileInput) (_ uuid.UUID, _ *uuid.UUID, _ uuid.UUID, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.ResolveChain", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.ResolveChain", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ResolveChain(ctx, orgID, company, branch, profile)
}

func (m *CorProfileLoggerMiddleware) UpdateBranch(ctx context.Context, id uuid.UUID, companyID uuid.UUID, req *models.UpdateCorBranchRequest) (_ *models.CorBranchDetails, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.UpdateBranch", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.UpdateBranch", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateBranch(ctx, id, companyID, req)
}

func (m *CorProfileLoggerMiddleware) UpdateCompany(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCorCompanyRequest) (_ *models.CorCompanyDetails, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.UpdateCompany", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.UpdateCompany", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateCompany(ctx, id, orgID, req)
}

func (m *CorProfileLoggerMiddleware) UpdateGuest(ctx context.Context, id uuid.UUID, profileID uuid.UUID, req *models.UpdateCorporateGuestRequest) (_ *models.CorporateGuest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.UpdateGuest", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.UpdateGuest", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateGuest(ctx, id, profileID, req)
}

func (m *CorProfileLoggerMiddleware) UpdateProfile(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCorProfileRequest) (_ *models.CorProfile, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorProfile.UpdateProfile", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorProfile.UpdateProfile", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateProfile(ctx, id, orgID, req)
}
