// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type CorporateBookingRequestLoggerMiddleware struct {
	next interfaces.CorporateBookingRequestInterface
}

func NewCorporateBookingRequestLoggerMiddleware(next interfaces.CorporateBookingRequestInterface) interfaces.CorporateBookingRequestInterface {
	return &CorporateBookingRequestLoggerMiddleware{next: next}
}

func (m *CorporateBookingRequestLoggerMiddleware) Approve(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.Approve", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.Approve", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Approve(ctx, id, orgID)
}

func (m *CorporateBookingRequestLoggerMiddleware) ApproveFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.ApproveFromWorkflow", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.ApproveFromWorkflow", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ApproveFromWorkflow(ctx, id, orgID)
}

func (m *CorporateBookingRequestLoggerMiddleware) Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.Cancel", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.Cancel", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Cancel(ctx, id, orgID)
}

func (m *CorporateBookingRequestLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.CorporateBookingRequest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id, orgID)
}

func (m *CorporateBookingRequestLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID, bookingType string, status string, page int, pageSize int) (_ []models.CorporateBookingRequest, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID, bookingType, status, page, pageSize)
}

func (m *CorporateBookingRequestLoggerMiddleware) Reject(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.Reject", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.Reject", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Reject(ctx, id, orgID)
}

func (m *CorporateBookingRequestLoggerMiddleware) RejectFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.RejectFromWorkflow", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.RejectFromWorkflow", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RejectFromWorkflow(ctx, id, orgID)
}

func (m *CorporateBookingRequestLoggerMiddleware) SubmitAccommodation(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitAccommodationRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.SubmitAccommodation", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.SubmitAccommodation", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SubmitAccommodation(ctx, orgID, webUserID, req)
}

func (m *CorporateBookingRequestLoggerMiddleware) SubmitEventBooking(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitEventBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.SubmitEventBooking", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.SubmitEventBooking", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SubmitEventBooking(ctx, orgID, webUserID, req)
}

func (m *CorporateBookingRequestLoggerMiddleware) SubmitMealBooking(ctx context.Context, orgID uuid.UUID, webUserID uuid.UUID, req *models.SubmitMealBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.SubmitMealBooking", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.SubmitMealBooking", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SubmitMealBooking(ctx, orgID, webUserID, req)
}

func (m *CorporateBookingRequestLoggerMiddleware) WalkInAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.SubmitAccommodationRequest, matReq *models.MaterialiseRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.WalkInAccommodation", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.WalkInAccommodation", zap.Duration("took", time.Since(start)))
	}()
	return m.next.WalkInAccommodation(ctx, orgID, branchID, req, matReq)
}

func (m *CorporateBookingRequestLoggerMiddleware) WalkInEvent(ctx context.Context, orgID uuid.UUID, req *models.SubmitEventBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.WalkInEvent", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.WalkInEvent", zap.Duration("took", time.Since(start)))
	}()
	return m.next.WalkInEvent(ctx, orgID, req)
}

func (m *CorporateBookingRequestLoggerMiddleware) WalkInMeal(ctx context.Context, orgID uuid.UUID, req *models.SubmitMealBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("CorporateBookingRequest.WalkInMeal", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("CorporateBookingRequest.WalkInMeal", zap.Duration("took", time.Since(start)))
	}()
	return m.next.WalkInMeal(ctx, orgID, req)
}
