// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type DashboardLoggerMiddleware struct {
	next interfaces.DashboardInterface
}

func NewDashboardLoggerMiddleware(next interfaces.DashboardInterface) interfaces.DashboardInterface {
	return &DashboardLoggerMiddleware{next: next}
}

func (m *DashboardLoggerMiddleware) GetBookings(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (_ *models.DashboardBookings, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Dashboard.GetBookings", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Dashboard.GetBookings", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetBookings(ctx, orgID, branchID)
}

func (m *DashboardLoggerMiddleware) GetInvoices(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (_ *models.DashboardInvoices, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Dashboard.GetInvoices", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Dashboard.GetInvoices", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetInvoices(ctx, orgID, branchID)
}

func (m *DashboardLoggerMiddleware) GetOrders(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (_ *models.DashboardOrders, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Dashboard.GetOrders", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Dashboard.GetOrders", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetOrders(ctx, orgID, branchID)
}

func (m *DashboardLoggerMiddleware) GetSummary(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (_ *models.DashboardSummary, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Dashboard.GetSummary", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Dashboard.GetSummary", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetSummary(ctx, orgID, branchID)
}
