// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type GuestAuthLoggerMiddleware struct {
	next interfaces.GuestAuthInterface
}

func NewGuestAuthLoggerMiddleware(next interfaces.GuestAuthInterface) interfaces.GuestAuthInterface {
	return &GuestAuthLoggerMiddleware{next: next}
}

func (m *GuestAuthLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID) (_ *models.Guest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("GuestAuth.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("GuestAuth.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id)
}

func (m *GuestAuthLoggerMiddleware) Login(ctx context.Context, emailAddr string, password string) (_ *models.Guest, _ string, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("GuestAuth.Login", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("GuestAuth.Login", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Login(ctx, emailAddr, password)
}

func (m *GuestAuthLoggerMiddleware) Register(ctx context.Context, req *models.GuestRegisterRequest) (_ *models.Guest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("GuestAuth.Register", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("GuestAuth.Register", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Register(ctx, req)
}

func (m *GuestAuthLoggerMiddleware) ResetPassword(ctx context.Context, emailAddr string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("GuestAuth.ResetPassword", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("GuestAuth.ResetPassword", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ResetPassword(ctx, emailAddr)
}

func (m *GuestAuthLoggerMiddleware) UpdateProfile(ctx context.Context, id uuid.UUID, req *models.GuestUpdateRequest) (_ *models.Guest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("GuestAuth.UpdateProfile", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("GuestAuth.UpdateProfile", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateProfile(ctx, id, req)
}
