// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type IndividualBookingRequestLoggerMiddleware struct {
	next interfaces.IndividualBookingRequestInterface
}

func NewIndividualBookingRequestLoggerMiddleware(next interfaces.IndividualBookingRequestInterface) interfaces.IndividualBookingRequestInterface {
	return &IndividualBookingRequestLoggerMiddleware{next: next}
}

func (m *IndividualBookingRequestLoggerMiddleware) Approve(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.Approve", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.Approve", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Approve(ctx, id, orgID)
}

func (m *IndividualBookingRequestLoggerMiddleware) ApproveFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.ApproveFromWorkflow", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.ApproveFromWorkflow", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ApproveFromWorkflow(ctx, id, orgID)
}

func (m *IndividualBookingRequestLoggerMiddleware) Cancel(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.Cancel", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.Cancel", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Cancel(ctx, id, orgID)
}

func (m *IndividualBookingRequestLoggerMiddleware) CancelForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.CancelForWebUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.CancelForWebUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CancelForWebUser(ctx, id, webUserID)
}

func (m *IndividualBookingRequestLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.IndividualBookingRequest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id, orgID)
}

func (m *IndividualBookingRequestLoggerMiddleware) GetForWebUser(ctx context.Context, id uuid.UUID, webUserID uuid.UUID) (_ *models.IndividualBookingRequest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.GetForWebUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.GetForWebUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetForWebUser(ctx, id, webUserID)
}

func (m *IndividualBookingRequestLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID, status string, page int, pageSize int) (_ []models.IndividualBookingRequest, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID, status, page, pageSize)
}

func (m *IndividualBookingRequestLoggerMiddleware) ListForWebUser(ctx context.Context, webUserID uuid.UUID, page int, pageSize int) (_ []models.IndividualBookingRequest, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.ListForWebUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.ListForWebUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListForWebUser(ctx, webUserID, page, pageSize)
}

func (m *IndividualBookingRequestLoggerMiddleware) Reject(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.Reject", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.Reject", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Reject(ctx, id, orgID)
}

func (m *IndividualBookingRequestLoggerMiddleware) RejectFromWorkflow(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.RejectFromWorkflow", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.RejectFromWorkflow", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RejectFromWorkflow(ctx, id, orgID)
}

func (m *IndividualBookingRequestLoggerMiddleware) Submit(ctx context.Context, guestID uuid.UUID, req *models.SubmitIndividualBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.Submit", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.Submit", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Submit(ctx, guestID, req)
}

func (m *IndividualBookingRequestLoggerMiddleware) SubmitEvent(ctx context.Context, guestID uuid.UUID, req *models.SubmitEventBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.SubmitEvent", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.SubmitEvent", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SubmitEvent(ctx, guestID, req)
}

func (m *IndividualBookingRequestLoggerMiddleware) SubmitMeal(ctx context.Context, guestID uuid.UUID, req *models.SubmitMealBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.SubmitMeal", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.SubmitMeal", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SubmitMeal(ctx, guestID, req)
}

func (m *IndividualBookingRequestLoggerMiddleware) WalkInAccommodation(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.SubmitIndividualBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.WalkInAccommodation", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.WalkInAccommodation", zap.Duration("took", time.Since(start)))
	}()
	return m.next.WalkInAccommodation(ctx, orgID, branchID, req)
}

func (m *IndividualBookingRequestLoggerMiddleware) WalkInEvent(ctx context.Context, orgID uuid.UUID, req *models.SubmitEventBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.WalkInEvent", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.WalkInEvent", zap.Duration("took", time.Since(start)))
	}()
	return m.next.WalkInEvent(ctx, orgID, req)
}

func (m *IndividualBookingRequestLoggerMiddleware) WalkInMeal(ctx context.Context, orgID uuid.UUID, req *models.SubmitMealBookingRequest) (_ *models.Booking, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("IndividualBookingRequest.WalkInMeal", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("IndividualBookingRequest.WalkInMeal", zap.Duration("took", time.Since(start)))
	}()
	return m.next.WalkInMeal(ctx, orgID, req)
}
