// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type InvoiceLoggerMiddleware struct {
	next interfaces.InvoiceInterface
}

func NewInvoiceLoggerMiddleware(next interfaces.InvoiceInterface) interfaces.InvoiceInterface {
	return &InvoiceLoggerMiddleware{next: next}
}

func (m *InvoiceLoggerMiddleware) GenerateForBooking(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.GenerateForBooking", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.GenerateForBooking", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GenerateForBooking(ctx, bookingID, orgID)
}

func (m *InvoiceLoggerMiddleware) GetByBookingID(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) (_ *models.Invoice, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.GetByBookingID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.GetByBookingID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByBookingID(ctx, bookingID, orgID)
}

func (m *InvoiceLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.Invoice, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id, orgID)
}

func (m *InvoiceLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, status string, clientType string, page int, pageSize int) (_ []models.Invoice, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID, branchID, status, clientType, page, pageSize)
}

func (m *InvoiceLoggerMiddleware) PostBookingCharge(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID, req *models.PostBookingChargeRequest) (_ *models.Invoice, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.PostBookingCharge", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.PostBookingCharge", zap.Duration("took", time.Since(start)))
	}()
	return m.next.PostBookingCharge(ctx, bookingID, orgID, req)
}

func (m *InvoiceLoggerMiddleware) RecalculateRoomCharge(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.RecalculateRoomCharge", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.RecalculateRoomCharge", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RecalculateRoomCharge(ctx, bookingID, orgID)
}

func (m *InvoiceLoggerMiddleware) RegenerateRoomInvoice(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.RegenerateRoomInvoice", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.RegenerateRoomInvoice", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RegenerateRoomInvoice(ctx, bookingID, orgID)
}

func (m *InvoiceLoggerMiddleware) SendInvoiceEmail(ctx context.Context, id uuid.UUID, orgID uuid.UUID, pdf []byte) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.SendInvoiceEmail", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.SendInvoiceEmail", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SendInvoiceEmail(ctx, id, orgID, pdf)
}

func (m *InvoiceLoggerMiddleware) SendPaymentConfirmationEmail(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.SendPaymentConfirmationEmail", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.SendPaymentConfirmationEmail", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SendPaymentConfirmationEmail(ctx, id, orgID)
}

func (m *InvoiceLoggerMiddleware) UpdateDueDate(ctx context.Context, bookingID uuid.UUID, orgID uuid.UUID, dueDate time.Time) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.UpdateDueDate", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.UpdateDueDate", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateDueDate(ctx, bookingID, orgID, dueDate)
}

func (m *InvoiceLoggerMiddleware) UpdateStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateInvoiceStatusRequest) (_ *models.Invoice, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Invoice.UpdateStatus", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Invoice.UpdateStatus", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateStatus(ctx, id, orgID, req)
}
