// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type MealCollectionLoggerMiddleware struct {
	next interfaces.MealCollectionInterface
}

func NewMealCollectionLoggerMiddleware(next interfaces.MealCollectionInterface) interfaces.MealCollectionInterface {
	return &MealCollectionLoggerMiddleware{next: next}
}

func (m *MealCollectionLoggerMiddleware) AssignCard(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.AssignCardRequest) (_ *models.MealCard, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.AssignCard", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.AssignCard", zap.Duration("took", time.Since(start)))
	}()
	return m.next.AssignCard(ctx, orgID, branchID, req)
}

func (m *MealCollectionLoggerMiddleware) Collect(ctx context.Context, orgID uuid.UUID, sessionID uuid.UUID, staffID uuid.UUID, staffName string, req *models.MealCollectRequest) (_ *models.MealCollectionResult, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.Collect", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.Collect", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Collect(ctx, orgID, sessionID, staffID, staffName, req)
}

func (m *MealCollectionLoggerMiddleware) CreateSession(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.MealSessionCreateRequest) (_ *models.ResidentMealSession, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.CreateSession", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.CreateSession", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateSession(ctx, orgID, branchID, req)
}

func (m *MealCollectionLoggerMiddleware) DeleteSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.DeleteSession", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.DeleteSession", zap.Duration("took", time.Since(start)))
	}()
	return m.next.DeleteSession(ctx, id, orgID)
}

func (m *MealCollectionLoggerMiddleware) GetCurrentStay(ctx context.Context, orgID uuid.UUID, roomID uuid.UUID) (_ *models.CurrentStay, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.GetCurrentStay", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.GetCurrentStay", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetCurrentStay(ctx, orgID, roomID)
}

func (m *MealCollectionLoggerMiddleware) GetSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.ResidentMealSession, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.GetSession", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.GetSession", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetSession(ctx, id, orgID)
}

func (m *MealCollectionLoggerMiddleware) ListCards(ctx context.Context, orgID uuid.UUID, roomID *uuid.UUID, status string) (_ []models.MealCard, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.ListCards", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.ListCards", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListCards(ctx, orgID, roomID, status)
}

func (m *MealCollectionLoggerMiddleware) ListCollections(ctx context.Context, sessionID uuid.UUID, orgID uuid.UUID) (_ []models.MealCollectionLogEntry, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.ListCollections", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.ListCollections", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListCollections(ctx, sessionID, orgID)
}

func (m *MealCollectionLoggerMiddleware) ListSessions(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, status string, mealPeriod string, page int, pageSize int) (_ *models.PaginatedMealSessions, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.ListSessions", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.ListSessions", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListSessions(ctx, orgID, branchID, status, mealPeriod, page, pageSize)
}

func (m *MealCollectionLoggerMiddleware) ReplaceCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.ReplaceCardRequest) (_ *models.MealCard, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.ReplaceCard", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.ReplaceCard", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ReplaceCard(ctx, id, orgID, req)
}

func (m *MealCollectionLoggerMiddleware) UpdateCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateCardRequest) (_ *models.MealCard, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.UpdateCard", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.UpdateCard", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateCard(ctx, id, orgID, req)
}

func (m *MealCollectionLoggerMiddleware) UpdateGracePeriod(ctx context.Context, id uuid.UUID, orgID uuid.UUID, minutes int) (_ *models.ResidentMealSession, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.UpdateGracePeriod", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.UpdateGracePeriod", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateGracePeriod(ctx, id, orgID, minutes)
}

func (m *MealCollectionLoggerMiddleware) UpdateSession(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.MealSessionUpdateRequest) (_ *models.ResidentMealSession, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.UpdateSession", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.UpdateSession", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateSession(ctx, id, orgID, req)
}

func (m *MealCollectionLoggerMiddleware) UpdateSessionStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (_ *models.ResidentMealSession, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.UpdateSessionStatus", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.UpdateSessionStatus", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateSessionStatus(ctx, id, orgID, status)
}

func (m *MealCollectionLoggerMiddleware) VoidCard(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.MealCard, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("MealCollection.VoidCard", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("MealCollection.VoidCard", zap.Duration("took", time.Since(start)))
	}()
	return m.next.VoidCard(ctx, id, orgID)
}
