// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type MenuLoggerMiddleware struct {
	next interfaces.MenuInterface
}

func NewMenuLoggerMiddleware(next interfaces.MenuInterface) interfaces.MenuInterface {
	return &MenuLoggerMiddleware{next: next}
}

func (m *MenuLoggerMiddleware) CreateMenuItem(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.CreateMenuItemRequest) (_ *models.MenuItem, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Menu.CreateMenuItem", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Menu.CreateMenuItem", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CreateMenuItem(ctx, orgID, branchID, req)
}

func (m *MenuLoggerMiddleware) DeleteMenuItem(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Menu.DeleteMenuItem", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Menu.DeleteMenuItem", zap.Duration("took", time.Since(start)))
	}()
	return m.next.DeleteMenuItem(ctx, id, orgID)
}

func (m *MenuLoggerMiddleware) GetMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, category string, page int, pageSize int) (_ *models.MenuResponse, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Menu.GetMenu", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Menu.GetMenu", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetMenu(ctx, orgID, branchID, category, page, pageSize)
}

func (m *MenuLoggerMiddleware) GetMenuItemByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.MenuItem, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Menu.GetMenuItemByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Menu.GetMenuItemByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetMenuItemByID(ctx, id, orgID)
}

func (m *MenuLoggerMiddleware) GuestGetMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, category string, page int, pageSize int) (_ *models.MenuResponse, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Menu.GuestGetMenu", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Menu.GuestGetMenu", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GuestGetMenu(ctx, orgID, branchID, category, page, pageSize)
}

func (m *MenuLoggerMiddleware) UpdateMenuItem(ctx context.Context, id uuid.UUID, orgID uuid.UUID, req *models.UpdateMenuItemRequest) (_ *models.MenuItem, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Menu.UpdateMenuItem", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Menu.UpdateMenuItem", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateMenuItem(ctx, id, orgID, req)
}

func (m *MenuLoggerMiddleware) UpsertMenu(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.UpdateMenuRequest, category string, page int, pageSize int) (_ *models.MenuResponse, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Menu.UpsertMenu", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Menu.UpsertMenu", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpsertMenu(ctx, orgID, branchID, req, category, page, pageSize)
}
