// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
	"lodge-system/internal/repository"
)

type OrderLoggerMiddleware struct {
	next interfaces.OrderInterface
}

func NewOrderLoggerMiddleware(next interfaces.OrderInterface) interfaces.OrderInterface {
	return &OrderLoggerMiddleware{next: next}
}

func (m *OrderLoggerMiddleware) AddItems(ctx context.Context, orderID uuid.UUID, orgID uuid.UUID, req *models.AddOrderItemsRequest) (_ *models.Order, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.AddItems", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.AddItems", zap.Duration("took", time.Since(start)))
	}()
	return m.next.AddItems(ctx, orderID, orgID, req)
}

func (m *OrderLoggerMiddleware) CloseAllOrders(ctx context.Context, orgID uuid.UUID) (_ int64, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.CloseAllOrders", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.CloseAllOrders", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CloseAllOrders(ctx, orgID)
}

func (m *OrderLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.Order, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id, orgID)
}

func (m *OrderLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, orderType string, status string, bookingID *uuid.UUID, from *time.Time, to *time.Time, page int, pageSize int) (_ []models.Order, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID, branchID, orderType, status, bookingID, from, to, page, pageSize)
}

func (m *OrderLoggerMiddleware) ListCheckedInGuests(ctx context.Context, orgID uuid.UUID) (_ []repository.InHouseGuest, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.ListCheckedInGuests", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.ListCheckedInGuests", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListCheckedInGuests(ctx, orgID)
}

func (m *OrderLoggerMiddleware) PlaceOrder(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.PlaceOrderRequest) (_ *models.Order, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.PlaceOrder", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.PlaceOrder", zap.Duration("took", time.Since(start)))
	}()
	return m.next.PlaceOrder(ctx, orgID, branchID, req)
}

func (m *OrderLoggerMiddleware) PlaceWalkInOrder(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, req *models.PlaceWalkInOrderRequest) (_ *models.Order, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.PlaceWalkInOrder", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.PlaceWalkInOrder", zap.Duration("took", time.Since(start)))
	}()
	return m.next.PlaceWalkInOrder(ctx, orgID, branchID, req)
}

func (m *OrderLoggerMiddleware) RemoveItem(ctx context.Context, itemID uuid.UUID, orderID uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.RemoveItem", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.RemoveItem", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RemoveItem(ctx, itemID, orderID, orgID)
}

func (m *OrderLoggerMiddleware) UpdateBarStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (_ *models.Order, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.UpdateBarStatus", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.UpdateBarStatus", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateBarStatus(ctx, id, orgID, status)
}

func (m *OrderLoggerMiddleware) UpdateKitchenStatus(ctx context.Context, id uuid.UUID, orgID uuid.UUID, status string) (_ *models.Order, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Order.UpdateKitchenStatus", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Order.UpdateKitchenStatus", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateKitchenStatus(ctx, id, orgID, status)
}
