// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type OrganizationSettingsLoggerMiddleware struct {
	next interfaces.OrganizationSettingsInterface
}

func NewOrganizationSettingsLoggerMiddleware(next interfaces.OrganizationSettingsInterface) interfaces.OrganizationSettingsInterface {
	return &OrganizationSettingsLoggerMiddleware{next: next}
}

func (m *OrganizationSettingsLoggerMiddleware) Get(ctx context.Context, orgID uuid.UUID) (_ *models.OrganizationSettings, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("OrganizationSettings.Get", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("OrganizationSettings.Get", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Get(ctx, orgID)
}

func (m *OrganizationSettingsLoggerMiddleware) Upsert(ctx context.Context, orgID uuid.UUID, req *models.UpdateOrganizationSettingsRequest) (_ *models.OrganizationSettings, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("OrganizationSettings.Upsert", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("OrganizationSettings.Upsert", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Upsert(ctx, orgID, req)
}
