// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type PasswordPolicyLoggerMiddleware struct {
	next interfaces.PasswordPolicyInterface
}

func NewPasswordPolicyLoggerMiddleware(next interfaces.PasswordPolicyInterface) interfaces.PasswordPolicyInterface {
	return &PasswordPolicyLoggerMiddleware{next: next}
}

func (m *PasswordPolicyLoggerMiddleware) CalculateLockoutTime(ctx context.Context, orgID ...uuid.UUID) (_ time.Time) {
	start := time.Now()
	defer func() {
		zap.L().Info("PasswordPolicy.CalculateLockoutTime", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CalculateLockoutTime(ctx, orgID...)
}

func (m *PasswordPolicyLoggerMiddleware) CalculatePasswordExpiry(ctx context.Context, orgID ...uuid.UUID) (_ *time.Time) {
	start := time.Now()
	defer func() {
		zap.L().Info("PasswordPolicy.CalculatePasswordExpiry", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CalculatePasswordExpiry(ctx, orgID...)
}

func (m *PasswordPolicyLoggerMiddleware) CheckAccountLockout(ctx context.Context, user *models.User) (_ bool, _ string) {
	start := time.Now()
	defer func() {
		zap.L().Info("PasswordPolicy.CheckAccountLockout", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CheckAccountLockout(ctx, user)
}

func (m *PasswordPolicyLoggerMiddleware) CheckPasswordExpiry(ctx context.Context, user *models.User) (_ bool, _ bool, _ int) {
	start := time.Now()
	defer func() {
		zap.L().Info("PasswordPolicy.CheckPasswordExpiry", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CheckPasswordExpiry(ctx, user)
}

func (m *PasswordPolicyLoggerMiddleware) GetPolicy(ctx context.Context, orgID ...uuid.UUID) (_ *models.PasswordPolicy) {
	start := time.Now()
	defer func() {
		zap.L().Info("PasswordPolicy.GetPolicy", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetPolicy(ctx, orgID...)
}

func (m *PasswordPolicyLoggerMiddleware) GetSessionTimeout(ctx context.Context, orgID ...uuid.UUID) (_ int) {
	start := time.Now()
	defer func() {
		zap.L().Info("PasswordPolicy.GetSessionTimeout", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetSessionTimeout(ctx, orgID...)
}

func (m *PasswordPolicyLoggerMiddleware) LoadGlobalPolicy(ctx context.Context) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("PasswordPolicy.LoadGlobalPolicy", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("PasswordPolicy.LoadGlobalPolicy", zap.Duration("took", time.Since(start)))
	}()
	return m.next.LoadGlobalPolicy(ctx)
}

func (m *PasswordPolicyLoggerMiddleware) RecordPasswordChange(ctx context.Context, userID uuid.UUID, passwordHash string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("PasswordPolicy.RecordPasswordChange", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("PasswordPolicy.RecordPasswordChange", zap.Duration("took", time.Since(start)))
	}()
	return m.next.RecordPasswordChange(ctx, userID, passwordHash)
}

func (m *PasswordPolicyLoggerMiddleware) ShouldLockAccount(ctx context.Context, failedAttempts int, orgID ...uuid.UUID) (_ bool) {
	start := time.Now()
	defer func() {
		zap.L().Info("PasswordPolicy.ShouldLockAccount", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ShouldLockAccount(ctx, failedAttempts, orgID...)
}

func (m *PasswordPolicyLoggerMiddleware) UpsertPolicy(ctx context.Context, orgID uuid.UUID, req *models.CreatePasswordPolicyRequest) (_ *models.PasswordPolicy, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("PasswordPolicy.UpsertPolicy", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("PasswordPolicy.UpsertPolicy", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpsertPolicy(ctx, orgID, req)
}

func (m *PasswordPolicyLoggerMiddleware) ValidateNewPassword(ctx context.Context, userID uuid.UUID, newPassword string, currentPasswordHash string, orgID ...uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("PasswordPolicy.ValidateNewPassword", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("PasswordPolicy.ValidateNewPassword", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ValidateNewPassword(ctx, userID, newPassword, currentPasswordHash, orgID...)
}
