// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type ReviewLoggerMiddleware struct {
	next interfaces.ReviewInterface
}

func NewReviewLoggerMiddleware(next interfaces.ReviewInterface) interfaces.ReviewInterface {
	return &ReviewLoggerMiddleware{next: next}
}

func (m *ReviewLoggerMiddleware) GetSummary(ctx context.Context) (_ *models.RatingSummary, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Review.GetSummary", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Review.GetSummary", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetSummary(ctx)
}

func (m *ReviewLoggerMiddleware) Submit(ctx context.Context, userID uuid.UUID, req *models.SubmitReviewRequest) (_ *models.Review, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Review.Submit", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Review.Submit", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Submit(ctx, userID, req)
}
