// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type RoleLoggerMiddleware struct {
	next interfaces.RoleInterface
}

func NewRoleLoggerMiddleware(next interfaces.RoleInterface) interfaces.RoleInterface {
	return &RoleLoggerMiddleware{next: next}
}

func (m *RoleLoggerMiddleware) GetAllRoles(ctx context.Context, orgID uuid.UUID) (_ []models.Role, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Role.GetAllRoles", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Role.GetAllRoles", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetAllRoles(ctx, orgID)
}

func (m *RoleLoggerMiddleware) InitializePredefinedRoles(ctx context.Context) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Role.InitializePredefinedRoles", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Role.InitializePredefinedRoles", zap.Duration("took", time.Since(start)))
	}()
	return m.next.InitializePredefinedRoles(ctx)
}
