// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type RoomLoggerMiddleware struct {
	next interfaces.RoomInterface
}

func NewRoomLoggerMiddleware(next interfaces.RoomInterface) interfaces.RoomInterface {
	return &RoomLoggerMiddleware{next: next}
}

func (m *RoomLoggerMiddleware) Create(ctx context.Context, room *models.Room, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.Create", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.Create", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Create(ctx, room, orgID)
}

func (m *RoomLoggerMiddleware) Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.Delete", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.Delete", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Delete(ctx, id, orgID)
}

func (m *RoomLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.Room, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id, orgID)
}

func (m *RoomLoggerMiddleware) GetByIDUnscoped(ctx context.Context, id uuid.UUID) (_ *models.Room, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.GetByIDUnscoped", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.GetByIDUnscoped", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByIDUnscoped(ctx, id)
}

func (m *RoomLoggerMiddleware) GuestList(ctx context.Context, orgID *uuid.UUID, branchID *uuid.UUID, roomType string, orgName string, isAvailable *bool, page int, pageSize int) (_ []models.Room, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.GuestList", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.GuestList", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GuestList(ctx, orgID, branchID, roomType, orgName, isAvailable, page, pageSize)
}

func (m *RoomLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, roomType string, isAvailable *bool, page int, pageSize int) (_ []models.Room, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID, branchID, roomType, isAvailable, page, pageSize)
}

func (m *RoomLoggerMiddleware) ListAvailable(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, checkIn time.Time, checkOut time.Time, roomType string) (_ []models.Room, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.ListAvailable", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.ListAvailable", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListAvailable(ctx, orgID, branchID, checkIn, checkOut, roomType)
}

func (m *RoomLoggerMiddleware) ListRoomStatus(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID) (_ []models.RoomStatus, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.ListRoomStatus", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.ListRoomStatus", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListRoomStatus(ctx, orgID, branchID)
}

func (m *RoomLoggerMiddleware) SetAvailability(ctx context.Context, id uuid.UUID, orgID uuid.UUID, available bool) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.SetAvailability", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.SetAvailability", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SetAvailability(ctx, id, orgID, available)
}

func (m *RoomLoggerMiddleware) Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.Room) (_ *models.Room, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.Update", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.Update", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Update(ctx, id, orgID, updates)
}

func (m *RoomLoggerMiddleware) UpdateImages(ctx context.Context, id uuid.UUID, orgID uuid.UUID, images []string) (_ *models.Room, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Room.UpdateImages", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Room.UpdateImages", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateImages(ctx, id, orgID, images)
}
