// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type UserLoggerMiddleware struct {
	next interfaces.UserInterface
}

func NewUserLoggerMiddleware(next interfaces.UserInterface) interfaces.UserInterface {
	return &UserLoggerMiddleware{next: next}
}

func (m *UserLoggerMiddleware) ChangePassword(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.ChangePassword", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.ChangePassword", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ChangePassword(ctx, userID, oldPassword, newPassword)
}

func (m *UserLoggerMiddleware) ChangeUserRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (_ *models.User, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.ChangeUserRole", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.ChangeUserRole", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ChangeUserRole(ctx, userID, roleID)
}

func (m *UserLoggerMiddleware) DeactivateUser(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.DeactivateUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.DeactivateUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.DeactivateUser(ctx, id)
}

func (m *UserLoggerMiddleware) DeleteUser(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.DeleteUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.DeleteUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.DeleteUser(ctx, id, orgID)
}

func (m *UserLoggerMiddleware) GetAllUsers(ctx context.Context) (_ []models.User, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.GetAllUsers", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.GetAllUsers", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetAllUsers(ctx)
}

func (m *UserLoggerMiddleware) GetByEmail(ctx context.Context, emailAddr string) (_ *models.User, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.GetByEmail", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.GetByEmail", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByEmail(ctx, emailAddr)
}

func (m *UserLoggerMiddleware) GetUserByID(ctx context.Context, id uuid.UUID) (_ *models.User, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.GetUserByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.GetUserByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetUserByID(ctx, id)
}

func (m *UserLoggerMiddleware) ListUsers(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, search string, roleID *uuid.UUID, isActive *bool, page int, pageSize int) (_ []models.User, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.ListUsers", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.ListUsers", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ListUsers(ctx, orgID, branchID, search, roleID, isActive, page, pageSize)
}

func (m *UserLoggerMiddleware) LockUser(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.LockUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.LockUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.LockUser(ctx, id)
}

func (m *UserLoggerMiddleware) Login(ctx context.Context, emailAddr string, pwd string) (_ map[string]interface{}, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.Login", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.Login", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Login(ctx, emailAddr, pwd)
}

func (m *UserLoggerMiddleware) LoginWithOrg(ctx context.Context, emailAddr string, pwd string, orgID uuid.UUID) (_ map[string]interface{}, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.LoginWithOrg", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.LoginWithOrg", zap.Duration("took", time.Since(start)))
	}()
	return m.next.LoginWithOrg(ctx, emailAddr, pwd, orgID)
}

func (m *UserLoggerMiddleware) Register(ctx context.Context, user *models.User) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.Register", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.Register", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Register(ctx, user)
}

func (m *UserLoggerMiddleware) ResetPassword(ctx context.Context, userID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.ResetPassword", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.ResetPassword", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ResetPassword(ctx, userID)
}

func (m *UserLoggerMiddleware) UnlockUser(ctx context.Context, id uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.UnlockUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.UnlockUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UnlockUser(ctx, id)
}

func (m *UserLoggerMiddleware) UpdateUser(ctx context.Context, updates *models.User) (_ *models.User, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.UpdateUser", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.UpdateUser", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateUser(ctx, updates)
}

func (m *UserLoggerMiddleware) UpdateUserFull(ctx context.Context, id uuid.UUID, callerID uuid.UUID, fullName string, newEmail string, pwd string, roleName string, status string, branchID *uuid.UUID) (_ *models.User, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("User.UpdateUserFull", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("User.UpdateUserFull", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateUserFull(ctx, id, callerID, fullName, newEmail, pwd, roleName, status, branchID)
}
