// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type VenueLoggerMiddleware struct {
	next interfaces.VenueInterface
}

func NewVenueLoggerMiddleware(next interfaces.VenueInterface) interfaces.VenueInterface {
	return &VenueLoggerMiddleware{next: next}
}

func (m *VenueLoggerMiddleware) Create(ctx context.Context, venue *models.Venue, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.Create", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.Create", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Create(ctx, venue, orgID)
}

func (m *VenueLoggerMiddleware) Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.Delete", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.Delete", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Delete(ctx, id, orgID)
}

func (m *VenueLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (_ *models.Venue, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id, orgID)
}

func (m *VenueLoggerMiddleware) GetByIDUnscoped(ctx context.Context, id uuid.UUID) (_ *models.Venue, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.GetByIDUnscoped", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.GetByIDUnscoped", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByIDUnscoped(ctx, id)
}

func (m *VenueLoggerMiddleware) GuestList(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, venueType string, from *time.Time, to *time.Time) (_ []models.Venue, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.GuestList", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.GuestList", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GuestList(ctx, orgID, branchID, venueType, from, to)
}

func (m *VenueLoggerMiddleware) List(ctx context.Context, orgID uuid.UUID, branchID *uuid.UUID, venueType string, isAvailable *bool, from *time.Time, to *time.Time, page int, pageSize int) (_ []models.Venue, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.List", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.List", zap.Duration("took", time.Since(start)))
	}()
	return m.next.List(ctx, orgID, branchID, venueType, isAvailable, from, to, page, pageSize)
}

func (m *VenueLoggerMiddleware) SetAvailability(ctx context.Context, id uuid.UUID, orgID uuid.UUID, available bool) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.SetAvailability", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.SetAvailability", zap.Duration("took", time.Since(start)))
	}()
	return m.next.SetAvailability(ctx, id, orgID, available)
}

func (m *VenueLoggerMiddleware) Update(ctx context.Context, id uuid.UUID, orgID uuid.UUID, updates *models.Venue) (_ *models.Venue, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.Update", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.Update", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Update(ctx, id, orgID, updates)
}

func (m *VenueLoggerMiddleware) UpdateImages(ctx context.Context, id uuid.UUID, orgID uuid.UUID, images []string) (_ *models.Venue, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Venue.UpdateImages", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Venue.UpdateImages", zap.Duration("took", time.Since(start)))
	}()
	return m.next.UpdateImages(ctx, id, orgID, images)
}
