// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type WebUserAuthLoggerMiddleware struct {
	next interfaces.WebUserAuthInterface
}

func NewWebUserAuthLoggerMiddleware(next interfaces.WebUserAuthInterface) interfaces.WebUserAuthInterface {
	return &WebUserAuthLoggerMiddleware{next: next}
}

func (m *WebUserAuthLoggerMiddleware) ChangePassword(ctx context.Context, id uuid.UUID, oldPassword string, newPassword string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("WebUserAuth.ChangePassword", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("WebUserAuth.ChangePassword", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ChangePassword(ctx, id, oldPassword, newPassword)
}

func (m *WebUserAuthLoggerMiddleware) GetByID(ctx context.Context, id uuid.UUID) (_ *models.WebUser, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("WebUserAuth.GetByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("WebUserAuth.GetByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetByID(ctx, id)
}

func (m *WebUserAuthLoggerMiddleware) Login(ctx context.Context, req *models.WebUserLoginRequest) (_ *models.WebUser, _ string, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("WebUserAuth.Login", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("WebUserAuth.Login", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Login(ctx, req)
}

func (m *WebUserAuthLoggerMiddleware) Register(ctx context.Context, req *models.WebUserRegisterRequest) (_ *models.WebUser, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("WebUserAuth.Register", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("WebUserAuth.Register", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Register(ctx, req)
}

func (m *WebUserAuthLoggerMiddleware) Update(ctx context.Context, id uuid.UUID, req *models.WebUserUpdateRequest) (_ *models.WebUser, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("WebUserAuth.Update", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("WebUserAuth.Update", zap.Duration("took", time.Since(start)))
	}()
	return m.next.Update(ctx, id, req)
}
