// Code generated by cmd/gen-interfaces. DO NOT EDIT.

package logger

import (
	"context"
	"time"

	"go.uber.org/zap"

	"lodge-system/internal/interfaces"
	"lodge-system/internal/models"
)

type WorkflowLoggerMiddleware struct {
	next interfaces.WorkflowInterface
}

func NewWorkflowLoggerMiddleware(next interfaces.WorkflowInterface) interfaces.WorkflowInterface {
	return &WorkflowLoggerMiddleware{next: next}
}

func (m *WorkflowLoggerMiddleware) CancelInstance(ctx context.Context, taskID string, orgID string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Workflow.CancelInstance", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Workflow.CancelInstance", zap.Duration("took", time.Since(start)))
	}()
	return m.next.CancelInstance(ctx, taskID, orgID)
}

func (m *WorkflowLoggerMiddleware) GetAllOrgTasks(ctx context.Context, orgID string, branchID string, statusFilter string, page int, pageSize int) (_ []models.AssignedTask, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Workflow.GetAllOrgTasks", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Workflow.GetAllOrgTasks", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetAllOrgTasks(ctx, orgID, branchID, statusFilter, page, pageSize)
}

func (m *WorkflowLoggerMiddleware) GetInstanceByTaskID(ctx context.Context, taskID string, orgID string) (_ *models.WorkflowInstance, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Workflow.GetInstanceByTaskID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Workflow.GetInstanceByTaskID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetInstanceByTaskID(ctx, taskID, orgID)
}

func (m *WorkflowLoggerMiddleware) GetInstanceHistory(ctx context.Context, instanceID string, orgID string) (_ []models.WorkflowHistory, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Workflow.GetInstanceHistory", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Workflow.GetInstanceHistory", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetInstanceHistory(ctx, instanceID, orgID)
}

func (m *WorkflowLoggerMiddleware) GetMyTasks(ctx context.Context, orgID string, userID string, statusFilter string, page int, pageSize int) (_ []models.AssignedTask, _ int, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Workflow.GetMyTasks", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Workflow.GetMyTasks", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetMyTasks(ctx, orgID, userID, statusFilter, page, pageSize)
}

func (m *WorkflowLoggerMiddleware) GetTaskByID(ctx context.Context, taskID string, orgID string) (_ *models.AssignedTask, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Workflow.GetTaskByID", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Workflow.GetTaskByID", zap.Duration("took", time.Since(start)))
	}()
	return m.next.GetTaskByID(ctx, taskID, orgID)
}

func (m *WorkflowLoggerMiddleware) InitiateWorkflow(ctx context.Context, workflowType models.WorkflowType, taskDetails models.TaskDetails, initiatorID string, priority string, dueDate interface{}, orgID string) (_ *models.WorkflowInstance, err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Workflow.InitiateWorkflow", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Workflow.InitiateWorkflow", zap.Duration("took", time.Since(start)))
	}()
	return m.next.InitiateWorkflow(ctx, workflowType, taskDetails, initiatorID, priority, dueDate, orgID)
}

func (m *WorkflowLoggerMiddleware) ProcessAction(ctx context.Context, instanceID string, action string, performedByID string, comments string, orgID string) (err error) {
	start := time.Now()
	defer func() {
		if err != nil {
			zap.L().Error("Workflow.ProcessAction", zap.Duration("took", time.Since(start)), zap.Error(err))
			return
		}
		zap.L().Info("Workflow.ProcessAction", zap.Duration("took", time.Since(start)))
	}()
	return m.next.ProcessAction(ctx, instanceID, action, performedByID, comments, orgID)
}
